import 'item.dart';
import 'dart:math';

class Shop {
  List<Item> menuSelection(String selection) {
    switch (selection) {
      case 'lightWeapon':
        {
          return this.lightWeapons;
        }
        break;

      case 'heavyWeapon':
        {
          return this.heavyWeapons;
        }
        break;
      case 'rangedWeapon':
        {
          return this.rangedWeapons;
        }
        break;
      case 'magicWeapon':
        {
          return this.magicWeapons;
        }
        break;
      case 'armor':
        {
          return this.armor;
        }
        break;
      case 'resources':
        {
          return this.resources;
        }
        break;
    }

    return [];
  }

  Item randomResourceRange(int min, int max) {
    int randomNumber = 0;
    bool itemNotFound = true;

    while (itemNotFound) {
      randomNumber = Random().nextInt(this.resources.length);

      if (this.resources[randomNumber].value <= max &&
          this.resources[randomNumber].value >= min) {
        itemNotFound = false;
        return this.resources[randomNumber];
      }
    }

    return null;
  }

  Item randomItemRange(int min, int max) {
    List<String> shopMenu = [
      'lightWeapons',
      'heavyWeapons',
      'rangedWeapons',
      'magicWeapons',
      'armor',
    ];

    int menuSelection;
    int randomItem;

    bool itemNotFound = true;

    while (itemNotFound) {
      menuSelection = Random().nextInt(shopMenu.length);

      switch (shopMenu[menuSelection]) {
        case 'lightWeapons':
          randomItem = Random().nextInt(this.lightWeapons.length);

          if (this.lightWeapons[randomItem].value <= max &&
              this.lightWeapons[randomItem].value >= min) {
            itemNotFound = false;
            return this.lightWeapons[randomItem];
          }

          break;

        case 'heavyWeapons':
          randomItem = Random().nextInt(this.heavyWeapons.length);

          if (this.heavyWeapons[randomItem].value <= max &&
              this.heavyWeapons[randomItem].value >= min) {
            itemNotFound = false;
            return this.heavyWeapons[randomItem];
          }

          break;

        case 'rangedWeapons':
          randomItem = Random().nextInt(this.rangedWeapons.length);

          if (this.rangedWeapons[randomItem].value <= max &&
              this.rangedWeapons[randomItem].value >= min) {
            itemNotFound = false;
            return this.rangedWeapons[randomItem];
          }

          break;

        case 'magicWeapons':
          randomItem = Random().nextInt(this.magicWeapons.length);

          if (this.magicWeapons[randomItem].value <= max &&
              this.magicWeapons[randomItem].value >= min) {
            itemNotFound = false;
            return this.magicWeapons[randomItem];
          }

          break;

        case 'armor':
          randomItem = Random().nextInt(this.armor.length);

          if (this.armor[randomItem].value <= max &&
              this.armor[randomItem].value >= min) {
            itemNotFound = false;
            return this.armor[randomItem];
          }
          break;
      }
    }

    return null;
  }

  //Item(this.icon, this.name, this.itemClass, this.inventorySpace,  this.description, this.pDamage, this.pArmor, this.mDamage, this.mArmor,this.weight,this.uses,this.value,);
  List<Item> lightWeapons = [
    Item(
      icon: 'baton',
      name: 'BATON',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A defensive weapon.',
      pDamage: 0,
      pArmor: 1,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'dagger',
      name: 'DAGGER',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A very sharp knife.',
      pDamage: 1,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'mace',
      name: 'MACE',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A bat made out of metal.',
      pDamage: 2,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 3,
      uses: 0,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'claw',
      name: 'CLAW',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A metal claw you can hold.',
      pDamage: 1,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 0,
      value: 200,
      enchant: 0,
    ),
    Item(
      icon: 'axe',
      name: 'AXE',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A normal axe.',
      pDamage: 2,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 2,
      uses: 0,
      value: 200,
      enchant: 0,
    ),
    Item(
      icon: 'shortSword',
      name: 'SHORT SWORD',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A small sword.',
      pDamage: 1,
      pArmor: 1,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 300,
      enchant: 0,
    ),
    Item(
      icon: 'shortSpear',
      name: 'SHORT SPEAR',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A pole with a pointy edge.',
      pDamage: 2,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 300,
      enchant: 0,
    ),
    Item(
      icon: 'rapier',
      name: 'RAPIER',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A sword made for pocking.',
      pDamage: 3,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 2,
      uses: 0,
      value: 400,
      enchant: 0,
    ),
    Item(
      icon: 'sword',
      name: 'SWORD',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A normal sword.',
      pDamage: 2,
      pArmor: 2,
      mDamage: 0,
      mArmor: 0,
      weight: 4,
      uses: 0,
      value: 400,
      enchant: 0,
    ),
    Item(
      icon: 'morningStar',
      name: 'MORNING STAR',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A bat with a ball full of spikes at the end.',
      pDamage: 5,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 6,
      uses: 0,
      value: 400,
      enchant: 0,
    ),
    Item(
      icon: 'saber',
      name: 'SABER',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A sword with a curved blade.',
      pDamage: 4,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 3,
      uses: 0,
      value: 500,
      enchant: 0,
    ),
    Item(
      icon: 'longSword',
      name: 'LONG SWORD',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A sword with a long blade.',
      pDamage: 3,
      pArmor: 2,
      mDamage: 0,
      mArmor: 0,
      weight: 5,
      uses: 0,
      value: 500,
      enchant: 0,
    ),
  ];

  List<Item> heavyWeapons = [
    Item(
      icon: 'longSpear',
      name: 'LONG SPEAR',
      itemClass: 'heavyWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A long pole with a pointy edge.',
      pDamage: 3,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 2,
      uses: 0,
      value: 300,
      enchant: 0,
    ),
    Item(
      icon: 'quarterstaff',
      name: 'QUARTERSTAFF',
      itemClass: 'heavyWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A pole made out of wood or metal.',
      pDamage: 1,
      pArmor: 3,
      mDamage: 0,
      mArmor: 0,
      weight: 4,
      uses: 0,
      value: 300,
      enchant: 0,
    ),
    Item(
      icon: 'doubleSword',
      name: 'DOUBLE SWORD',
      itemClass: 'heavyWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A pole with a blade on each end.',
      pDamage: 5,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 5,
      uses: 0,
      value: 400,
      enchant: 0,
    ),
    Item(
      icon: 'trident',
      name: 'TRIDENT',
      itemClass: 'heavyWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A pole with three points at the end.',
      pDamage: 4,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 3,
      uses: 0,
      value: 400,
      enchant: 0,
    ),
    Item(
      icon: 'battleAxe',
      name: 'BATTLE AXE',
      itemClass: 'heavyWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'An axe with a blade on both sides.',
      pDamage: 7,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 8,
      uses: 0,
      value: 500,
      enchant: 0,
    ),
    Item(
      icon: 'halberd',
      name: 'HALBERD',
      itemClass: 'heavyWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A long spear with an axe at the end.',
      pDamage: 6,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 6,
      uses: 0,
      value: 500,
      enchant: 0,
    ),
    Item(
      icon: 'warHammer',
      name: 'WAR HAMMER',
      itemClass: 'heavyWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A pole with a heavy object at the end.',
      pDamage: 8,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 9,
      uses: 0,
      value: 600,
      enchant: 0,
    ),
    Item(
      icon: 'greatSword',
      name: 'GREAT SWORD',
      itemClass: 'heavyWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A sword that is very long and heavy.',
      pDamage: 5,
      pArmor: 2,
      mDamage: 0,
      mArmor: 0,
      weight: 7,
      uses: 0,
      value: 600,
      enchant: 0,
    ),
  ];

  List<Item> rangedWeapons = [
    Item(
      icon: 'blowgun',
      name: 'BLOWGUN',
      itemClass: 'rangedWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A tube that shoots darts.',
      pDamage: 1,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 0,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'boomerang',
      name: 'BOOMERANG',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'You throw, it comes back.',
      pDamage: 1,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'javelins',
      name: 'JAVELINS',
      itemClass: 'thrownWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A spear you can throw.',
      pDamage: 2,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      uses: 5,
      value: 200,
      enchant: 0,
    ),
    Item(
      icon: 'shortBow',
      name: 'SHORT BOW',
      itemClass: 'rangedWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A small bow.',
      pDamage: 3,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 3,
      uses: 0,
      value: 300,
      enchant: 0,
    ),
    Item(
      icon: 'kunai',
      name: 'KUNAI',
      itemClass: 'thrownWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'Little knifes you can throw.',
      pDamage: 3,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      uses: 5,
      value: 300,
      enchant: 0,
    ),
    Item(
      icon: 'handCrossbow',
      name: 'HAND CROSSBOW',
      itemClass: 'rangedWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A weapon that shoots small bolts.',
      pDamage: 3,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 2,
      uses: 0,
      value: 400,
      enchant: 0,
    ),
    Item(
      icon: 'longBow',
      name: 'LONG BOW',
      itemClass: 'rangedWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A bow that shoots arrows really far.',
      pDamage: 4,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 4,
      uses: 0,
      value: 400,
      enchant: 0,
    ),
    Item(
      icon: 'greatBow',
      name: 'GREAT BOW',
      itemClass: 'rangedWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A heavy bow that shoots arrows really, really far.',
      pDamage: 5,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 5,
      uses: 0,
      value: 500,
      enchant: 0,
    ),
    Item(
      icon: 'lightCrossbow',
      name: 'LIGHT CROSSBOW',
      itemClass: 'rangedWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A weapon that shoots bolts.',
      pDamage: 4,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 3,
      uses: 0,
      value: 500,
      enchant: 0,
    ),
    Item(
      icon: 'handCannon',
      name: 'HAND CANNON',
      itemClass: 'rangedWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A weapon that shoots bullets.',
      pDamage: 3,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 0,
      value: 600,
      enchant: 0,
    ),
    Item(
      icon: 'heavyCrossbow',
      name: 'HEAVY CROSSBOW',
      itemClass: 'rangedWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A powerful weapom that shoots heavy bolts.',
      pDamage: 7,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 8,
      uses: 0,
      value: 600,
      enchant: 0,
    ),
    Item(
      icon: 'musket',
      name: 'MUSKET',
      itemClass: 'rangedWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A weapon that shoots bigger bullets.',
      pDamage: 5,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 3,
      uses: 0,
      value: 700,
      enchant: 0,
    ),
  ];

  List<Item> magicWeapons = [
    Item(
      icon: 'magicOrb',
      name: 'MAGIC ORB',
      itemClass: 'magicWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A cristal ball with magic powers.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 1,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 200,
      enchant: 0,
    ),
    Item(
      icon: 'grenades',
      name: 'GRENADES',
      itemClass: 'thrownWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A shell that explodes on impact.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 2,
      mArmor: 0,
      weight: 1,
      uses: 5,
      value: 200,
      enchant: 0,
    ),
    Item(
      icon: 'wand',
      name: 'WAND',
      itemClass: 'magicWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A stick with magic powers.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 1,
      mArmor: 0,
      weight: 0,
      uses: 0,
      value: 300,
      enchant: 0,
    ),
    Item(
      icon: 'ritualDagger',
      name: 'RITUAL DAGGER',
      itemClass: 'magicWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A dagger with a magic powers.',
      pDamage: 1,
      pArmor: 0,
      mDamage: 1,
      mArmor: 0,
      weight: 2,
      uses: 0,
      value: 300,
      enchant: 0,
    ),
    Item(
      icon: 'magicSword',
      name: 'MAGIC SWORD',
      itemClass: 'magicWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A sword with magic powers.',
      pDamage: 1,
      pArmor: 1,
      mDamage: 1,
      mArmor: 0,
      weight: 3,
      uses: 0,
      value: 400,
      enchant: 0,
    ),
    Item(
      icon: 'spellBook',
      name: 'SPELLBOOK',
      itemClass: 'magicWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A book with magic powers.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 2,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 500,
      enchant: 0,
    ),
    Item(
      icon: 'magicAxe',
      name: 'MAGIC AXE',
      itemClass: 'magicWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'An axe with magic powers.',
      pDamage: 2,
      pArmor: 0,
      mDamage: 2,
      mArmor: 0,
      weight: 4,
      uses: 0,
      value: 600,
      enchant: 0,
    ),
    Item(
      icon: 'magicStaff',
      name: 'MAGIC STAFF',
      itemClass: 'magicWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A staff with strong magic powers.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 5,
      mArmor: 0,
      weight: 5,
      uses: 0,
      value: 700,
      enchant: 0,
    ),
    Item(
      icon: 'ancientSword',
      name: 'ANCIENT SWORD',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'An ancient sword.',
      pDamage: 3,
      pArmor: 0,
      mDamage: 2,
      mArmor: 0,
      weight: 2,
      uses: 0,
      value: 1600,
      enchant: 0,
    ),
    Item(
      icon: 'ancientBow',
      name: 'ANCIENT BOW',
      itemClass: 'rangedWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'An ancient bow.',
      pDamage: 4,
      pArmor: 0,
      mDamage: 2,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 1600,
      enchant: 0,
    ),
    Item(
      icon: 'ancientWarAxe',
      name: 'ANCIENT WAR AXE',
      itemClass: 'heavyWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'An ancient war axe.',
      pDamage: 6,
      pArmor: 0,
      mDamage: 2,
      mArmor: 0,
      weight: 4,
      uses: 0,
      value: 1700,
      enchant: 0,
    ),
    Item(
      icon: 'ancientSpellbook',
      name: 'ANCIENT SPELLBOOK',
      itemClass: 'magicWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'An ancient spellbook.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 6,
      mArmor: 0,
      weight: 2,
      uses: 0,
      value: 1900,
      enchant: 0,
    ),
  ];

  List<Item> armor = [
    Item(
      icon: 'boots',
      name: 'BOOTS',
      itemClass: 'armor',
      inventorySpace: 'feet',
      action: 'EQUIP',
      description: 'Protects your feet.',
      pDamage: 0,
      pArmor: 1,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'gloves',
      name: 'GLOVES',
      itemClass: 'armor',
      inventorySpace: 'hands',
      action: 'EQUIP',
      description: 'Protects your hands.',
      pDamage: 0,
      pArmor: 1,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'buckler',
      name: 'BUCKLER',
      itemClass: 'armor',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A small shield.',
      pDamage: 0,
      pArmor: 1,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 0,
      value: 200,
      enchant: 0,
    ),

// I am removing so I have an even distribution of itens on this page

    // Item(
    //   icon: 'magicSandals',
    //   name: 'MAGIC SANDALS',
    //   itemClass: 'armor',
    //   inventorySpace: 'feet',
    //   description: 'It protects you from the elements.',
    //   pDamage: 0,
    //   pArmor: 0,
    //   mDamage: 0,
    //   mArmor: 1,
    //   weight: 1,
    //   uses: 0,
    //   value: 200,
    // ),
    Item(
      icon: 'helmet',
      name: 'HELMET',
      itemClass: 'armor',
      inventorySpace: 'head',
      action: 'EQUIP',
      description: 'Protects your head.',
      pDamage: 0,
      pArmor: 2,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 300,
      enchant: 0,
    ),
    Item(
      icon: 'lightShield',
      name: 'SHIELD',
      itemClass: 'armor',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A normal shield.',
      pDamage: 0,
      pArmor: 2,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 300,
      enchant: 0,
    ),
    Item(
      icon: 'lightArmor',
      name: 'LIGHT ARMOR',
      itemClass: 'armor',
      inventorySpace: 'body',
      action: 'EQUIP',
      description: 'Protects your body.',
      pDamage: 0,
      pArmor: 4,
      mDamage: 0,
      mArmor: 0,
      weight: 4,
      uses: 0,
      value: 400,
      enchant: 0,
    ),
    Item(
      icon: 'magicRobe',
      name: 'MAGIC ROBE',
      itemClass: 'armor',
      inventorySpace: 'body',
      action: 'EQUIP',
      description: 'A robe that resists magic.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 2,
      weight: 2,
      uses: 0,
      value: 400,
      enchant: 0,
    ),
    Item(
      icon: 'heavyShield',
      name: 'HEAVY SHIELD',
      itemClass: 'armor',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A heavy shield.',
      pDamage: 0,
      pArmor: 4,
      mDamage: 0,
      mArmor: 0,
      weight: 3,
      uses: 0,
      value: 500,
      enchant: 0,
    ),
    Item(
      icon: 'fullHelmet',
      name: 'FULL HELMET',
      itemClass: 'armor',
      inventorySpace: 'head',
      action: 'EQUIP',
      description: 'Protects your head and face.',
      pDamage: 0,
      pArmor: 4,
      mDamage: 0,
      mArmor: 0,
      weight: 2,
      uses: 0,
      value: 600,
      enchant: 0,
    ),
    Item(
      icon: 'magicShield',
      name: 'MAGIC SHIELD',
      itemClass: 'armor',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A shield that resists magic.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 3,
      weight: 3,
      uses: 0,
      value: 600,
      enchant: 0,
    ),
    Item(
      icon: 'heavyArmor',
      name: 'HEAVY ARMOR',
      itemClass: 'armor',
      inventorySpace: 'body',
      action: 'EQUIP',
      description: 'A armor that protects your body.',
      pDamage: 0,
      pArmor: 7,
      mDamage: 0,
      mArmor: 0,
      weight: 7,
      uses: 0,
      value: 700,
      enchant: 0,
    ),
    Item(
      icon: 'ancientGloves',
      name: 'ANCIENT GLOVES',
      itemClass: 'armor',
      inventorySpace: 'hands',
      action: 'EQUIP',
      description: 'An ancient pair of gloves.',
      pDamage: 0,
      pArmor: 1,
      mDamage: 0,
      mArmor: 1,
      weight: 0,
      uses: 0,
      value: 800,
      enchant: 0,
    ),
    Item(
      icon: 'ancientBoots',
      name: 'ANCIENT BOOTS',
      itemClass: 'armor',
      inventorySpace: 'feet',
      action: 'EQUIP',
      description: 'An ancient pair of boots.',
      pDamage: 0,
      pArmor: 2,
      mDamage: 0,
      mArmor: 1,
      weight: 1,
      uses: 0,
      value: 900,
      enchant: 0,
    ),
    Item(
      icon: 'ancientHelmet',
      name: 'ANCIENT HELMET',
      itemClass: 'armor',
      inventorySpace: 'head',
      action: 'EQUIP',
      description: 'An ancient helmet.',
      pDamage: 0,
      pArmor: 4,
      mDamage: 0,
      mArmor: 2,
      weight: 2,
      uses: 0,
      value: 1500,
      enchant: 0,
    ),
    Item(
      icon: 'ancientShield',
      name: 'ANCIENT SHIELD',
      itemClass: 'armor',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'An ancient shield.',
      pDamage: 0,
      pArmor: 3,
      mDamage: 0,
      mArmor: 2,
      weight: 2,
      uses: 0,
      value: 1600,
      enchant: 0,
    ),
    Item(
      icon: 'ancientArmor',
      name: 'ANCIENT ARMOR',
      itemClass: 'armor',
      inventorySpace: 'body',
      action: 'EQUIP',
      description: 'An ancient armor.',
      pDamage: 0,
      pArmor: 5,
      mDamage: 0,
      mArmor: 2,
      weight: 3,
      uses: 0,
      value: 1600,
      enchant: 0,
    ),
  ];

  List<Item> resources = [
    Item(
      icon: 'bandages',
      name: 'BANDAGES',
      itemClass: 'resource',
      inventorySpace: 'consumable',
      action: 'USE',
      description: 'Stops bleeding.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 1,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'herbs',
      name: 'HERBS',
      itemClass: 'resource',
      inventorySpace: 'consumable',
      action: 'USE',
      description: 'Stops poisons.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 1,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'book',
      name: 'BOOK',
      itemClass: 'resource',
      inventorySpace: 'consumable',
      action: 'USE',
      description: 'Answers one question.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 1,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'tool',
      name: 'TOOL',
      itemClass: 'resource',
      inventorySpace: 'consumable',
      action: 'USE',
      description: 'Any simple tool.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 1,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'ammo',
      name: 'AMMO',
      itemClass: 'ammo',
      inventorySpace: 'consumable',
      action: 'RESTOCK',
      description: 'Anything you can shoot.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 5,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'food',
      name: 'FOOD',
      itemClass: 'resource',
      inventorySpace: 'consumable',
      action: 'EAT',
      description: 'Heals you a little.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 1,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'key',
      name: 'KEY',
      itemClass: 'resource',
      inventorySpace: 'consumable',
      action: 'USE',
      description: 'Unlocks anything.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 1,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'antidote',
      name: 'ANTIDOTE',
      itemClass: 'potion',
      inventorySpace: 'consumable',
      action: 'DRINK',
      description: 'Removes all effects.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 1,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'ward',
      name: 'WARD',
      itemClass: 'resource',
      inventorySpace: 'consumable',
      action: 'USE',
      description: 'Gives you vision of an area.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 1,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'resistancePotion',
      name: 'RESISTANCE POTION',
      itemClass: 'potion',
      inventorySpace: 'consumable',
      action: 'DRINK',
      description: 'Gives you magic resistance.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 1,
      value: 200,
      enchant: 0,
    ),
    Item(
      icon: 'healingPotion',
      name: 'HEALING POTION',
      itemClass: 'potion',
      inventorySpace: 'consumable',
      action: 'DRINK',
      description: 'Heals you a lot.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 1,
      value: 300,
      enchant: 0,
    ),
    Item(
      icon: 'magicRune',
      name: 'MAGIC RUNE',
      itemClass: 'magicRune',
      inventorySpace: 'consumable',
      action: 'ENCHANT',
      description: 'Enchants your gear.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 1,
      value: 600,
      enchant: 0,
    ),
  ];

//   List<Item> shopList = [
//     Item(0,'bonus','','','BONUS','Each background gives you a different bonus.',0,0,0,0,0,0,0,Image.asset('images/shop/00.png')),
//     Item(0,'shop','','','Shop','',0,0,0,0,0,0,0,Image.asset('images/shop/00.png')),
//     Item(0,'loot','','','Loot','',0,0,0,0,0,0,0,Image.asset('images/shop/00.png')),
//
//     //LIGHT
//
//     Item(1,'light','DEX','1hand','DAGGER','It is a knife with a very sharp edge designed for close combat.',0,0,0,0,0,0,100, Image.asset('images/shop/light1.png')),
//     Item(2,'light','DEX','1hand','BATON','It is a club with a handle and it is carried as a defensive weapon.',0,0,1,0,1,0,100, Image.asset('images/shop/light2.png')),
//     Item(3,'light','DEX','1hand','SICKLE','It is a curved blade with the sharp edge on the inside.',0,0,0,0,0,0,200, Image.asset('images/shop/light3.png')),
//     Item(4,'light','DEX','1hand','CLAW','A couple of blades designed to fit over the knuckles.',0,0,0,0,0,0,200, Image.asset('images/shop/light4.png')),
//     Item(5,'light','DEX','1hand','WHIP','It is a handle with a flexible line at the end. ',0,0,0,0,0,0,200, Image.asset('images/shop/light5.png')),
//     Item(6,'light','DEX','1hand','SHORT SPEAR','It is a stick with a pointy edge.',0,0,0,0,0,0,300, Image.asset('images/shop/light6.png')),
//     Item(7,'light','DEX','1hand','RAPPIER','It is a very light sword used for pocking.',0,0,0,0,0,0,300, Image.asset('images/shop/light7.png')),
//     Item(8,'light','DEX','1hand','NUNCHAKU','Two pieces of wood attached by a string. Requires a lot of coordination.',0,0,0,0,0,0,300, Image.asset('images/shop/light8.png')),
//     Item(9,'light','DEX','2hand','QUARTERSTAFF','A staff that can be used as a defensive weapon.',0,0,2,0,2,0,400, Image.asset('images/shop/light9.png')),
//     Item(10,'light','DEX','1hand','SABER','A sword with a curved blade and only one sharp edge.',1,0,0,0,1,0,400, Image.asset('images/shop/light10.png')),
//     Item(11,'light','DEX','2hand','DOUBLE SWORD','A stick with a blade on each end.',2,0,0,0,2,0,500, Image.asset('images/shop/light11.png')),
//     Item(12,'light','DEX','2hand','LONG SPEAR','A great weapon to keep your enemies at a distance.',1,0,0,0,1,0,500, Image.asset('images/shop/light12.png')),
//     Item(13,'light','DEX','2hand','TRIDENT','A heavier e more powerful spear with three points.',2,0,0,0,2,0,600, Image.asset('images/shop/light13.png')),
//
//     // 15 Item Count
//
//     //HEAVY
//
//
//     Item(1,'heavy','STR','1hand','CAESTUS','It is a fist weapon made out of steel.',0,0,0,0,0,0,100, Image.asset('images/shop/heavy1.png')),
//     Item(2,'heavy','STR','2hand','GARROTE','It is a chain, rope, wire or anything used to strangle a person.',0,0,0,0,0,0,100, Image.asset('images/shop/heavy2.png')),
//     Item(3,'heavy','STR','1hand','CLUB','It is a small bat made out of wood, metal or stone.',0,0,0,0,0,0,100, Image.asset('images/shop/heavy3.png')),
//     Item(4,'heavy','STR','1hand','WOOD AXE','A small axe used for chopping wood.',0,0,0,0,0,0,200, Image.asset('images/shop/heavy4.png')),
//     Item(5,'heavy','STR','1hand','SHORT SWORD','A small sword, great for fighting indoors.',0,0,0,0,0,0,300, Image.asset('images/shop/heavy5.png')),
//     Item(6,'heavy','STR','1hand','MACE','A club reinforced with a metal head.',1,0,0,0,1,0,300, Image.asset('images/shop/heavy6.png')),
//     Item(7,'heavy','STR','1hand','AXE','An axe with a longer blade and better grip. ',1,0,0,0,1,0,300, Image.asset('images/shop/heavy7.png')),
//     Item(8,'heavy','STR','1hand','MORNING STAR','A club with a steal ball with spikes at the end.',2,0,0,0,2,0,400, Image.asset('images/shop/heavy8.png')),
//     Item(9,'heavy','STR','1hand','SWORD','It is a very common weapon, used for pretty much any occasion.',1,0,0,0,1,0,400, Image.asset('images/shop/heavy9.png')),
//     Item(10,'heavy','STR','1hand','LONG SWORD','A sword with a longer blade.',2,0,0,0,2,0,500,Image.asset('images/shop/heavy10.png')),
//     Item(11,'heavy','STR','1hand','FLAIL','A ball of steel connected to a handle by a chain.',1,0,0,0,1,0,500,Image.asset('images/shop/heavy11.png')),
//     Item(12,'heavy','STR','1hand','BATTLE AXE','A heavy axe with blade on both sides.',2,0,0,0,2,0,500,Image.asset('images/shop/heavy12.png')),
//     Item(13,'heavy','STR','1hand','LANCE','A very long weapon, used mainly for jousting competitions.',3,0,0,0,3,0,600,Image.asset('images/shop/heavy13.png')),
//     Item(14,'heavy','STR','2hand','GREAT SWORD','A very long and heavy sword. Those who wield it properly are fearsome adversaries.',3,0,0,0,3,0,600,Image.asset('images/shop/heavy14.png')),
//     Item(15,'heavy','STR','2hand','HALBERD','A long spear with an axe at the end. Good for poking and slashing.',3,0,0,0,3,0,600,Image.asset('images/shop/heavy15.png')),
//     Item(16,'heavy','STR','2hand','WAR HAMMER','A staff with a heavy metal head. Great for crushing bones.',3,0,0,0,3,0,600,Image.asset('images/shop/heavy16.png')),
//
//     // 31 Item Count
//
//     //RANGED WEAPON
//
//     Item(1,'ranged','DEX','1hand','BOOMERANG','It is a thrown weapon that is designed to return to the thrower.',0,0,0,0,0,0,100,Image.asset('images/shop/ranged1.png')),
//     Item(2,'ranged','DEX','1hand','SLING','It is used to throw rocks, clay, or lead.',0,0,0,0,0,0,100,Image.asset('images/shop/ranged2.png')),
//     Item(3,'ranged','DEX','1hand','BLOW DART','It is a long tube for shooting light projectiles such as darts.',0,0,0,0,0,0,200,Image.asset('images/shop/ranged3.png')),
//     Item(4,'ranged','DEX','1hand','KUNAI','It is a blade with a ring on the handle that can be used for attaching a rope.',0,0,0,0,0,0,200,Image.asset('images/shop/ranged4.png')),
//     Item(5,'ranged','DEX','1hand','JAVELINS','Small spears that can be thrown at a target.',0,0,0,0,0,0,300,Image.asset('images/shop/ranged5.png')),
//     Item(6,'ranged','DEX','2hand','SHORT BOW','A ranged weapon that can shoot arrows.',0,0,0,0,0,0,300,Image.asset('images/shop/ranged6.png')),
//     Item(7,'ranged','DEX','2hand','LONG BOW','A longer bow that can shoot arrows even further.',0,0,0,0,0,0,400,Image.asset('images/shop/ranged7.png')),
//     Item(8,'ranged','DEX','1hand','HAND CANNON','A ranged weapon that can shoot bullets.',1,0,0,0,1,0,400,Image.asset('images/shop/ranged8.png')),
//     Item(9,'ranged','DEX','1hand','HAND CROSSBOW','A ranged weapon that shoots arrows. ',0,0,0,0,0,0,400,Image.asset('images/shop/ranged9.png')),
//     Item(10,'ranged','DEX','2hand','GREAT BOW','',1,0,0,0,1,0,500,Image.asset('images/shop/ranged10.png')),
//     Item(11,'ranged','DEX','1hand','LIGHT CROSSBOW','',1,0,0,0,1,0,500,Image.asset('images/shop/ranged11.png')),
//     Item(12,'ranged','STR','1hand','GRENADE','',0,1,0,0,1,0,500,Image.asset('images/shop/ranged12.png')),
//     Item(13,'ranged','DEX','2hand','MUSKET','',2,0,0,0,2,0,600,Image.asset('images/shop/ranged13.png')),
//     Item(14,'ranged','STR','2hand','HEAVY CROSSBOW','',2,0,0,0,2,0,600,Image.asset('images/shop/ranged14.png')),
//
//     // 45 Item Count
//
//     //MAGIC
//
//
//
//     Item(1,'magic','INT','CONSUMABLE','Blank Scroll','',0,0,0,0,0,1,100,Image.asset('images/shop/magic1.png')),
//     Item(2,'magic','INT','CONSUMABLE','Protection Scroll','',0,0,0,0,0,1,200,Image.asset('images/shop/magic2.png')),
//     Item(3,'magic','INT','CONSUMABLE','Healing Scroll','',0,0,0,0,0,1,300,Image.asset('images/shop/magic3.png')),
//     Item(4,'magic','INT','CONSUMABLE','Skill Scroll','',0,0,0,0,0,1,400,Image.asset('images/shop/magic4.png')),
//     Item(5,'magic','INT','CONSUMABLE','Attribute Scroll','',0,0,0,0,0,1,400,Image.asset('images/shop/magic5.png')),
//     Item(6,'magic','INT','CONSUMABLE','Ability Scroll','',0,0,0,0,0,1,400,Image.asset('images/shop/magic6.png')),
//     Item(7,'magic','INT','CONSUMABLE','Summoning Scroll','',0,0,0,0,0,1,500,Image.asset('images/shop/magic7.png')),
//     Item(8,'magic','INT','CONSUMABLE','Life Scroll','',0,0,0,0,0,1,600,Image.asset('images/shop/magic8.png')),
//     Item(9,'magic','INT','1hand','WAND','A wand is a thin, light-weight rod that has magical powers, allowing the user to cast spells.',0,0,0,0,0,0,200,Image.asset('images/shop/magic9.png')),
//     Item(10,'magic','INT','1hand','SPELLBOOK','',0,1,0,0,1,0,400,Image.asset('images/shop/magic10.png')),
//     Item(11,'magic','INT','2hand','MAGIC STAFF','',0,2,0,0,2,0,600,Image.asset('images/shop/magic11.png')),
//
//     // 56 Item Count
//
//
//     //ARMOR
//
//     Item(1,'armor','DEX','1hand','BUCKLER','It is a small shield used for deflecting attacks.',0,0,1,0,1,0,100,Image.asset('images/shop/armor1.png')),
//     Item(2,'armor','STR','1hand','LIGHT SHIELD','A shield used for intercepting attacks, whether from close-ranged or a distance.',0,0,1,0,1,0,200,Image.asset('images/shop/armor2.png')),
//     Item(3,'armor','STR','1hand','HEAVY SHIELD','',0,0,2,0,2,0,300,Image.asset('images/shop/armor3.png')),
//     Item(4,'armor','STR','1hand','TOWER SHIELD','',0,0,3,0,3,0,400,Image.asset('images/shop/armor4.png')),
//     Item(5,'armor','CON','body','LIGHT ARMOR','A light armor offers a bit of protection, prevent damage from being inflicted to the user.',0,0,1,0,1,0,200,Image.asset('images/shop/armor5.png')),
//     Item(6,'armor','CON','body','MEDIUM ARMOR','',0,0,2,0,2,0,300,Image.asset('images/shop/armor6.png')),
//     Item(7,'armor','CON','body','HEAVY ARMOR','',0,0,3,0,3,0,400,Image.asset('images/shop/armor7.png')),
//     Item(8,'armor','CON','body','FULL PLATE','',0,0,4,0,4,0,500,Image.asset('images/shop/armor8.png')),
//     Item(9,'armor','CON','feet','BOOTS','A boot is a type of footwear that covers and protects your feet.',0,0,1,0,1,0,100,Image.asset('images/shop/armor9.png')),
//     Item(10,'armor','CON','feet','GREAVES','',0,0,2,0,2,0,300,Image.asset('images/shop/armor10.png')),
//     Item(11,'armor','CON','hands','GLOVES','A glove is a garment covering the whole hand. It offers protection for your hands.',0,0,1,0,1,0,100,Image.asset('images/shop/armor11.png')),
//     Item(12,'armor','CON','hands','GAUNTLET','',0,0,2,0,2,0,300,Image.asset('images/shop/armor12.png')),
//     Item(13,'armor','CON','head','HELMET','A helmet is a form of protective gear worn to protect the head.',0,0,1,0,1,0,100,Image.asset('images/shop/armor13.png')),
//     Item(14,'armor','CON','head','FULL HELMET','',0,0,2,0,2,0,300,Image.asset('images/shop/armor14.png')),
//
//     // 70 Item Count
//
//     //RESOURCES
//
//     Item(1,'resource','','CONSUMABLE','Antidote','',0,0,0,0,0,1,100,Image.asset('images/shop/resource1.png')),
//     Item(2,'resource','','CONSUMABLE','Resistance Potion','',0,0,0,0,0,1,200,Image.asset('images/shop/resource2.png')),
//     Item(3,'resource','','CONSUMABLE','Healing Potion','',0,0,0,0,0,1,300,Image.asset('images/shop/resource3.png')),
//     Item(4,'resource','','CONSUMABLE','Magic Potion','',0,0,0,0,0,1,400,Image.asset('images/shop/resource4.png')),
//     Item(5,'resource','','CONSUMABLE','Invincibility Potion','',0,0,0,0,0,1,500,Image.asset('images/shop/resource5.png')),
//     Item(6,'resource','','CONSUMABLE','Life Potion','',0,0,0,0,0,1,600,Image.asset('images/shop/resource6.png')),
//     Item(7,'resource','','CONSUMABLE','Ammo','',1,0,0,0,1,5,100,Image.asset('images/shop/resource7.png')),
//     Item(8,'resource','','CONSUMABLE','Book','A book is a medium for recording information in the form of writing or images. When using the moves I KNOW or THAT GUY, spend the book to get a +2 on your roll.',0,0,0,0,0,1,100,Image.asset('images/shop/resource8.png')),
//     Item(9,'resource','','CONSUMABLE','Bandages','Spend your First Aid to heal 1D6.',0,0,0,0,0,1,100,Image.asset('images/shop/resource9.png')),
//     Item(10,'resource','','CONSUMABLE','Gear','Gear is a collection of useful tools such as chalk, staffs, spikes, ropes, ladder, etc. At anytime you can spend your gear, turning it into an object of your choice.',0,0,0,0,0,1,200,Image.asset('images/shop/resource10.png')),
//     Item(11,'resource','','CONSUMABLE','Key','You can spend your key to open any chest, lock or door.',0,0,0,0,0,1,200,Image.asset('images/shop/resource11.png')),
//     Item(12,'resource','','CONSUMABLE','Ward','',0,0,0,0,0,1,300,Image.asset('images/shop/resource12.png')),
//     Item(13,'resource','','CONSUMABLE','Magic Ammo','',0,2,0,0,1,5,500,Image.asset('images/shop/resource13.png')),
//
//     // 83 Item Count
//
//
//     //ENCHANTMENT
//
//     Item(12,'enchantment','','CONSUMABLE','Skill Charm','',0,0,0,0,0,1,600,Image.asset('images/shop/enchantment1.png')),
//     Item(9,'enchantment','','CONSUMABLE','Rune','',0,2,0,0,1,1,500,Image.asset('images/shop/enchantment2.png')),
//     Item(11,'enchantment','','CONSUMABLE','Life Charm','',0,0,0,0,0,1,600,Image.asset('images/shop/enchantment3.png')),
//
//     // 86 Item Count
//
//     //BONUS
//
//     Item(6,'bonus','','CONSUMABLE','Adaptation','',0,0,0,0,1,1,300,Image.asset('images/shop/bonus1.png')),
//     Item(8,'bonus','','CONSUMABLE','Free Action','',0,0,0,0,0,1,400,Image.asset('images/shop/bonus2.png')),
//     Item(7,'bonus','','CONSUMABLE','Luck Charm','',0,0,0,0,0,1,400,Image.asset('images/shop/bonus3.png')),
//
//     // 89 Item Count
//
//
//   ];
}
