import 'item.dart';
import 'dart:math';

class Shop {
  List<Item> menuSelection(String selection) {
    switch (selection) {
      case 'lightWeapon':
        {
          return this.lightWeapons;
        }
        break;

      case 'heavyWeapon':
        {
          return this.heavyWeapons;
        }
        break;
      case 'rangedWeapon':
        {
          return this.rangedWeapons;
        }
        break;
      case 'magicWeapon':
        {
          return this.magicWeapons;
        }
        break;
      case 'armor':
        {
          return this.armor;
        }
        break;
      case 'resources':
        {
          return this.resources;
        }
        break;
    }

    return [];
  }

  Item randomItemRange(int min, int max, String itemType) {
    List<String> shopMenu = [];
    switch (itemType) {
      case 'armor':
        shopMenu = [
          'armor',
        ];
        break;

      case 'weapon':
        shopMenu = [
          'lightWeapons',
          'heavyWeapons',
          'rangedWeapons',
          'magicWeapons',
        ];
        break;

      case 'item':
        shopMenu = [
          'lightWeapons',
          'heavyWeapons',
          'rangedWeapons',
          'magicWeapons',
          'armor',
        ];

        break;

      case 'resources':
        shopMenu = [
          'resources',
        ];
        break;
    }

    int menuSelection;
    int randomItem;

    bool itemNotFound = true;

    while (itemNotFound) {
      menuSelection = Random().nextInt(shopMenu.length);

      switch (shopMenu[menuSelection]) {
        case 'lightWeapons':
          randomItem = Random().nextInt(this.lightWeapons.length);

          if (this.lightWeapons[randomItem].value <= max &&
              this.lightWeapons[randomItem].value >= min) {
            itemNotFound = false;
            return this.lightWeapons[randomItem];
          }

          break;

        case 'heavyWeapons':
          randomItem = Random().nextInt(this.heavyWeapons.length);

          if (this.heavyWeapons[randomItem].value <= max &&
              this.heavyWeapons[randomItem].value >= min) {
            itemNotFound = false;
            return this.heavyWeapons[randomItem];
          }

          break;

        case 'rangedWeapons':
          randomItem = Random().nextInt(this.rangedWeapons.length);

          if (this.rangedWeapons[randomItem].value <= max &&
              this.rangedWeapons[randomItem].value >= min) {
            itemNotFound = false;
            return this.rangedWeapons[randomItem];
          }

          break;

        case 'magicWeapons':
          randomItem = Random().nextInt(this.magicWeapons.length);

          if (this.magicWeapons[randomItem].value <= max &&
              this.magicWeapons[randomItem].value >= min) {
            itemNotFound = false;
            return this.magicWeapons[randomItem];
          }

          break;

        case 'armor':
          randomItem = Random().nextInt(this.armor.length);

          if (this.armor[randomItem].value <= max &&
              this.armor[randomItem].value >= min) {
            itemNotFound = false;
            return this.armor[randomItem];
          }
          break;

        case 'resources':
          randomItem = Random().nextInt(this.resources.length);

          if (this.resources[randomItem].value <= max &&
              this.resources[randomItem].value >= min) {
            itemNotFound = false;
            return this.resources[randomItem];
          }
          break;
      }
    }

    return null;
  }

  //Item(this.icon, this.name, this.itemClass, this.inventorySpace,  this.description, this.pDamage, this.pArmor, this.mDamage, this.mArmor,this.weight,this.uses,this.value,);
  List<Item> lightWeapons = [
    Item(
      icon: 'baton',
      name: 'BATON',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A defensive weapon.',
      pDamage: 0,
      pArmor: 1,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 100,
      enchant: 0,
      maxRange: 20,
      minRange: 0,
    ),
    Item(
      icon: 'dagger',
      name: 'DAGGER',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A very sharp knife.',
      pDamage: 1,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 100,
      enchant: 0,
      maxRange: 20,
      minRange: 0,
    ),
    Item(
      icon: 'mace',
      name: 'MACE',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A bat made out of metal.',
      pDamage: 2,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 3,
      uses: 0,
      value: 100,
      enchant: 0,
      maxRange: 20,
      minRange: 0,
    ),
    Item(
      icon: 'claw',
      name: 'CLAW',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A metal claw you can hold.',
      pDamage: 1,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 0,
      value: 200,
      enchant: 0,
      maxRange: 20,
      minRange: 0,
    ),
    Item(
      icon: 'axe',
      name: 'AXE',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A normal axe.',
      pDamage: 2,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 2,
      uses: 0,
      value: 200,
      enchant: 0,
      maxRange: 25,
      minRange: 0,
    ),
    Item(
      icon: 'shortSword',
      name: 'SHORT SWORD',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A small sword.',
      pDamage: 1,
      pArmor: 1,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 300,
      enchant: 0,
      maxRange: 25,
      minRange: 0,
    ),
    Item(
      icon: 'shortSpear',
      name: 'SHORT SPEAR',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A pole with a pointy edge.',
      pDamage: 2,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 300,
      enchant: 0,
      maxRange: 30,
      minRange: 0,
    ),
    Item(
      icon: 'rapier',
      name: 'RAPIER',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A sword made for pocking.',
      pDamage: 3,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 2,
      uses: 0,
      value: 400,
      enchant: 0,
      maxRange: 25,
      minRange: 0,
    ),
    Item(
      icon: 'sword',
      name: 'SWORD',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A normal sword.',
      pDamage: 2,
      pArmor: 2,
      mDamage: 0,
      mArmor: 0,
      weight: 4,
      uses: 0,
      value: 400,
      enchant: 0,
      maxRange: 30,
      minRange: 0,
    ),
    Item(
      icon: 'morningStar',
      name: 'MORNING STAR',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A bat with a ball full of spikes at the end.',
      pDamage: 5,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 6,
      uses: 0,
      value: 400,
      enchant: 0,
      maxRange: 30,
      minRange: 0,
    ),
    Item(
      icon: 'saber',
      name: 'SABER',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A sword with a curved blade.',
      pDamage: 4,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 3,
      uses: 0,
      value: 500,
      enchant: 0,
      maxRange: 30,
      minRange: 0,
    ),
    Item(
      icon: 'longSword',
      name: 'LONG SWORD',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A sword with a long blade.',
      pDamage: 3,
      pArmor: 2,
      mDamage: 0,
      mArmor: 0,
      weight: 5,
      uses: 0,
      value: 500,
      enchant: 0,
      maxRange: 35,
      minRange: 0,
    ),
  ];

  List<Item> heavyWeapons = [
    Item(
      icon: 'longSpear',
      name: 'LONG SPEAR',
      itemClass: 'heavyWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A long pole with a pointy edge.',
      pDamage: 3,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 2,
      uses: 0,
      value: 300,
      enchant: 0,
      maxRange: 35,
      minRange: 0,
    ),
    Item(
      icon: 'quarterstaff',
      name: 'QUARTERSTAFF',
      itemClass: 'heavyWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A pole made out of wood or metal.',
      pDamage: 1,
      pArmor: 3,
      mDamage: 0,
      mArmor: 0,
      weight: 4,
      uses: 0,
      value: 300,
      enchant: 0,
      maxRange: 35,
      minRange: 0,
    ),
    Item(
      icon: 'doubleSword',
      name: 'DOUBLE SWORD',
      itemClass: 'heavyWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A pole with a blade on each end.',
      pDamage: 5,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 5,
      uses: 0,
      value: 400,
      enchant: 0,
      maxRange: 35,
      minRange: 0,
    ),
    Item(
      icon: 'trident',
      name: 'TRIDENT',
      itemClass: 'heavyWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A pole with three points at the end.',
      pDamage: 4,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 3,
      uses: 0,
      value: 400,
      enchant: 0,
      maxRange: 40,
      minRange: 0,
    ),
    Item(
      icon: 'battleAxe',
      name: 'BATTLE AXE',
      itemClass: 'heavyWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'An axe with a blade on both sides.',
      pDamage: 7,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 8,
      uses: 0,
      value: 500,
      enchant: 0,
      maxRange: 40,
      minRange: 0,
    ),
    Item(
      icon: 'halberd',
      name: 'HALBERD',
      itemClass: 'heavyWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A long spear with an axe at the end.',
      pDamage: 6,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 6,
      uses: 0,
      value: 500,
      enchant: 0,
      maxRange: 45,
      minRange: 0,
    ),
    Item(
      icon: 'warHammer',
      name: 'WAR HAMMER',
      itemClass: 'heavyWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A pole with a heavy object at the end.',
      pDamage: 8,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 9,
      uses: 0,
      value: 600,
      enchant: 0,
      maxRange: 40,
      minRange: 0,
    ),
    Item(
      icon: 'greatSword',
      name: 'GREAT SWORD',
      itemClass: 'heavyWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A sword that is very long and heavy.',
      pDamage: 5,
      pArmor: 2,
      mDamage: 0,
      mArmor: 0,
      weight: 7,
      uses: 0,
      value: 600,
      enchant: 0,
      maxRange: 45,
      minRange: 0,
    ),
  ];

  List<Item> rangedWeapons = [
    Item(
      icon: 'blowgun',
      name: 'BLOWGUN',
      itemClass: 'rangedWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A tube that shoots darts.',
      pDamage: 1,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 0,
      value: 100,
      enchant: 0,
      maxRange: 120,
      minRange: 0,
    ),
    Item(
      icon: 'boomerang',
      name: 'BOOMERANG',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'You throw, it comes back.',
      pDamage: 1,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 100,
      enchant: 0,
      maxRange: 100,
      minRange: 0,
    ),
    Item(
      icon: 'javelins',
      name: 'JAVELINS',
      itemClass: 'thrownWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A spear you can throw.',
      pDamage: 2,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      uses: 5,
      value: 200,
      enchant: 0,
      maxRange: 100,
      minRange: 0,
    ),
    Item(
      icon: 'shortBow',
      name: 'SHORT BOW',
      itemClass: 'rangedWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A small bow.',
      pDamage: 3,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 3,
      uses: 0,
      value: 300,
      enchant: 0,
      maxRange: 140,
      minRange: 0,
    ),
    Item(
      icon: 'kunai',
      name: 'KUNAI',
      itemClass: 'thrownWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'Little knifes you can throw.',
      pDamage: 2,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      uses: 3,
      value: 300,
      enchant: 0,
      maxRange: 100,
      minRange: 0,
    ),
    Item(
      icon: 'handCrossbow',
      name: 'HAND CROSSBOW',
      itemClass: 'rangedWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A weapon that shoots small bolts.',
      pDamage: 2,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 2,
      uses: 0,
      value: 400,
      enchant: 0,
      maxRange: 100,
      minRange: 0,
    ),
    Item(
      icon: 'longBow',
      name: 'LONG BOW',
      itemClass: 'rangedWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A bow that shoots arrows really far.',
      pDamage: 4,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 4,
      uses: 0,
      value: 400,
      enchant: 0,
      maxRange: 160,
      minRange: 0,
    ),
    Item(
      icon: 'greatBow',
      name: 'GREAT BOW',
      itemClass: 'rangedWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A heavy bow that shoots arrows really, really far.',
      pDamage: 5,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 5,
      uses: 0,
      value: 500,
      enchant: 0,
      maxRange: 180,
      minRange: 0,
    ),
    Item(
      icon: 'lightCrossbow',
      name: 'LIGHT CROSSBOW',
      itemClass: 'rangedWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A weapon that shoots bolts.',
      pDamage: 4,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 3,
      uses: 0,
      value: 500,
      enchant: 0,
      maxRange: 130,
      minRange: 0,
    ),
    Item(
      icon: 'handCannon',
      name: 'HAND CANNON',
      itemClass: 'rangedWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A weapon that shoots bullets.',
      pDamage: 3,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 0,
      value: 600,
      enchant: 0,
      maxRange: 120,
      minRange: 0,
    ),
    Item(
      icon: 'heavyCrossbow',
      name: 'HEAVY CROSSBOW',
      itemClass: 'rangedWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A powerful weapom that shoots heavy bolts.',
      pDamage: 7,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 8,
      uses: 0,
      value: 600,
      enchant: 0,
      maxRange: 140,
      minRange: 0,
    ),
    Item(
      icon: 'musket',
      name: 'MUSKET',
      itemClass: 'rangedWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A weapon that shoots bigger bullets.',
      pDamage: 5,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 3,
      uses: 0,
      value: 700,
      enchant: 0,
      maxRange: 140,
      minRange: 0,
    ),
  ];

  List<Item> magicWeapons = [
    Item(
      icon: 'magicOrb',
      name: 'MAGIC ORB',
      itemClass: 'magicWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A cristal ball with magic powers.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 1,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 200,
      enchant: 0,
      maxRange: 100,
      minRange: 0,
    ),
    Item(
      icon: 'grenades',
      name: 'GRENADES',
      itemClass: 'thrownWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A shell that explodes on impact.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 2,
      mArmor: 0,
      weight: 1,
      uses: 5,
      value: 200,
      enchant: 0,
      maxRange: 100,
      minRange: 0,
    ),
    Item(
      icon: 'wand',
      name: 'WAND',
      itemClass: 'magicWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A stick with magic powers.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 1,
      mArmor: 0,
      weight: 0,
      uses: 0,
      value: 300,
      enchant: 0,
      maxRange: 110,
      minRange: 0,
    ),
    Item(
      icon: 'ritualDagger',
      name: 'RITUAL DAGGER',
      itemClass: 'magicWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A dagger with a magic powers.',
      pDamage: 1,
      pArmor: 0,
      mDamage: 1,
      mArmor: 0,
      weight: 2,
      uses: 0,
      value: 300,
      enchant: 0,
      maxRange: 30,
      minRange: 0,
    ),
    Item(
      icon: 'magicSword',
      name: 'MAGIC SWORD',
      itemClass: 'magicWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A sword with magic powers.',
      pDamage: 1,
      pArmor: 1,
      mDamage: 1,
      mArmor: 0,
      weight: 3,
      uses: 0,
      value: 400,
      enchant: 0,
      maxRange: 40,
      minRange: 0,
    ),
    Item(
      icon: 'spellBook',
      name: 'SPELLBOOK',
      itemClass: 'magicWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A book with magic powers.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 2,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 500,
      enchant: 0,
      maxRange: 120,
      minRange: 0,
    ),
    Item(
      icon: 'magicAxe',
      name: 'MAGIC AXE',
      itemClass: 'magicWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'An axe with magic powers.',
      pDamage: 2,
      pArmor: 0,
      mDamage: 2,
      mArmor: 0,
      weight: 4,
      uses: 0,
      value: 600,
      enchant: 0,
      maxRange: 35,
      minRange: 0,
    ),
    Item(
      icon: 'magicStaff',
      name: 'MAGIC STAFF',
      itemClass: 'magicWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'A staff with strong magic powers.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 5,
      mArmor: 0,
      weight: 5,
      uses: 0,
      value: 700,
      enchant: 0,
      maxRange: 130,
      minRange: 0,
    ),
    Item(
      icon: 'ancientSword',
      name: 'ANCIENT SWORD',
      itemClass: 'lightWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'An ancient sword.',
      pDamage: 3,
      pArmor: 0,
      mDamage: 2,
      mArmor: 0,
      weight: 2,
      uses: 0,
      value: 1600,
      enchant: 0,
      maxRange: 55,
      minRange: 0,
    ),
    Item(
      icon: 'ancientBow',
      name: 'ANCIENT BOW',
      itemClass: 'rangedWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'An ancient bow.',
      pDamage: 4,
      pArmor: 0,
      mDamage: 2,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 1600,
      enchant: 0,
      maxRange: 220,
      minRange: 0,
    ),
    Item(
      icon: 'ancientWarAxe',
      name: 'ANCIENT WAR AXE',
      itemClass: 'heavyWeapon',
      inventorySpace: '2hand',
      action: 'EQUIP',
      description: 'An ancient war axe.',
      pDamage: 6,
      pArmor: 0,
      mDamage: 2,
      mArmor: 0,
      weight: 4,
      uses: 0,
      value: 1700,
      enchant: 0,
      maxRange: 60,
      minRange: 0,
    ),
    Item(
      icon: 'ancientSpellbook',
      name: 'ANCIENT SPELLBOOK',
      itemClass: 'magicWeapon',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'An ancient spellbook.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 6,
      mArmor: 0,
      weight: 2,
      uses: 0,
      value: 1900,
      enchant: 0,
      maxRange: 150,
      minRange: 0,
    ),
  ];

  List<Item> armor = [
    Item(
      icon: 'boots',
      name: 'BOOTS',
      itemClass: 'armor',
      inventorySpace: 'feet',
      action: 'EQUIP',
      description: 'Protects your feet.',
      pDamage: 0,
      pArmor: 1,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'gloves',
      name: 'GLOVES',
      itemClass: 'armor',
      inventorySpace: 'hands',
      action: 'EQUIP',
      description: 'Protects your hands.',
      pDamage: 0,
      pArmor: 1,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'buckler',
      name: 'BUCKLER',
      itemClass: 'armor',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A small shield.',
      pDamage: 0,
      pArmor: 1,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 0,
      value: 200,
      enchant: 0,
    ),

// I am removing so I have an even distribution of itens on this page

    // Item(
    //   icon: 'magicSandals',
    //   name: 'MAGIC SANDALS',
    //   itemClass: 'armor',
    //   inventorySpace: 'feet',
    //   description: 'It protects you from the elements.',
    //   pDamage: 0,
    //   pArmor: 0,
    //   mDamage: 0,
    //   mArmor: 1,
    //   weight: 1,
    //   uses: 0,
    //   value: 200,
    // ),
    Item(
      icon: 'helmet',
      name: 'HELMET',
      itemClass: 'armor',
      inventorySpace: 'head',
      action: 'EQUIP',
      description: 'Protects your head.',
      pDamage: 0,
      pArmor: 2,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 300,
      enchant: 0,
    ),
    Item(
      icon: 'lightShield',
      name: 'SHIELD',
      itemClass: 'armor',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A normal shield.',
      pDamage: 0,
      pArmor: 2,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      uses: 0,
      value: 300,
      enchant: 0,
    ),
    Item(
      icon: 'lightArmor',
      name: 'LIGHT ARMOR',
      itemClass: 'armor',
      inventorySpace: 'body',
      action: 'EQUIP',
      description: 'Protects your body.',
      pDamage: 0,
      pArmor: 4,
      mDamage: 0,
      mArmor: 0,
      weight: 4,
      uses: 0,
      value: 400,
      enchant: 0,
    ),
    Item(
      icon: 'magicRobe',
      name: 'MAGIC ROBE',
      itemClass: 'armor',
      inventorySpace: 'body',
      action: 'EQUIP',
      description: 'A robe that resists magic.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 2,
      weight: 2,
      uses: 0,
      value: 400,
      enchant: 0,
    ),
    Item(
      icon: 'heavyShield',
      name: 'HEAVY SHIELD',
      itemClass: 'armor',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A heavy shield.',
      pDamage: 0,
      pArmor: 4,
      mDamage: 0,
      mArmor: 0,
      weight: 3,
      uses: 0,
      value: 500,
      enchant: 0,
    ),
    Item(
      icon: 'fullHelmet',
      name: 'FULL HELMET',
      itemClass: 'armor',
      inventorySpace: 'head',
      action: 'EQUIP',
      description: 'Protects your head and face.',
      pDamage: 0,
      pArmor: 4,
      mDamage: 0,
      mArmor: 0,
      weight: 2,
      uses: 0,
      value: 600,
      enchant: 0,
    ),
    Item(
      icon: 'magicShield',
      name: 'MAGIC SHIELD',
      itemClass: 'armor',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'A shield that resists magic.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 3,
      weight: 3,
      uses: 0,
      value: 600,
      enchant: 0,
    ),
    Item(
      icon: 'heavyArmor',
      name: 'HEAVY ARMOR',
      itemClass: 'armor',
      inventorySpace: 'body',
      action: 'EQUIP',
      description: 'A armor that protects your body.',
      pDamage: 0,
      pArmor: 7,
      mDamage: 0,
      mArmor: 0,
      weight: 7,
      uses: 0,
      value: 700,
      enchant: 0,
    ),
    Item(
      icon: 'ancientGloves',
      name: 'ANCIENT GLOVES',
      itemClass: 'armor',
      inventorySpace: 'hands',
      action: 'EQUIP',
      description: 'An ancient pair of gloves.',
      pDamage: 0,
      pArmor: 1,
      mDamage: 0,
      mArmor: 1,
      weight: 0,
      uses: 0,
      value: 800,
      enchant: 0,
    ),
    Item(
      icon: 'ancientBoots',
      name: 'ANCIENT BOOTS',
      itemClass: 'armor',
      inventorySpace: 'feet',
      action: 'EQUIP',
      description: 'An ancient pair of boots.',
      pDamage: 0,
      pArmor: 2,
      mDamage: 0,
      mArmor: 1,
      weight: 1,
      uses: 0,
      value: 900,
      enchant: 0,
    ),
    Item(
      icon: 'ancientHelmet',
      name: 'ANCIENT HELMET',
      itemClass: 'armor',
      inventorySpace: 'head',
      action: 'EQUIP',
      description: 'An ancient helmet.',
      pDamage: 0,
      pArmor: 4,
      mDamage: 0,
      mArmor: 2,
      weight: 2,
      uses: 0,
      value: 1200,
      enchant: 0,
    ),
    Item(
      icon: 'ancientShield',
      name: 'ANCIENT SHIELD',
      itemClass: 'armor',
      inventorySpace: '1hand',
      action: 'EQUIP',
      description: 'An ancient shield.',
      pDamage: 0,
      pArmor: 3,
      mDamage: 0,
      mArmor: 2,
      weight: 2,
      uses: 0,
      value: 1600,
      enchant: 0,
    ),
    Item(
      icon: 'ancientArmor',
      name: 'ANCIENT ARMOR',
      itemClass: 'armor',
      inventorySpace: 'body',
      action: 'EQUIP',
      description: 'An ancient armor.',
      pDamage: 0,
      pArmor: 5,
      mDamage: 0,
      mArmor: 2,
      weight: 3,
      uses: 0,
      value: 1600,
      enchant: 0,
    ),
  ];

  List<Item> resources = [
    Item(
      icon: 'bandages',
      name: 'BANDAGES',
      itemClass: 'resource',
      inventorySpace: 'consumable',
      action: 'USE',
      description: 'Stops bleeding.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 1,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'herbs',
      name: 'HERBS',
      itemClass: 'resource',
      inventorySpace: 'consumable',
      action: 'USE',
      description: 'Stops poisons.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 1,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'book',
      name: 'BOOK',
      itemClass: 'resource',
      inventorySpace: 'consumable',
      action: 'USE',
      description: 'Answers one question.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 1,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'tool',
      name: 'TOOL',
      itemClass: 'resource',
      inventorySpace: 'consumable',
      action: 'USE',
      description: 'Any simple tool.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 1,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'ammo',
      name: 'AMMO',
      itemClass: 'ammo',
      inventorySpace: 'consumable',
      action: 'RESTOCK',
      description: 'Anything you can shoot.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 5,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'food',
      name: 'FOOD',
      itemClass: 'resource',
      inventorySpace: 'consumable',
      action: 'EAT',
      description: 'Heals you a little.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 1,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'key',
      name: 'KEY',
      itemClass: 'resource',
      inventorySpace: 'consumable',
      action: 'USE',
      description: 'Unlocks anything.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 1,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'antidote',
      name: 'ANTIDOTE',
      itemClass: 'potion',
      inventorySpace: 'consumable',
      action: 'DRINK',
      description: 'Removes all effects.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 1,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'ward',
      name: 'WARD',
      itemClass: 'resource',
      inventorySpace: 'consumable',
      action: 'USE',
      description: 'Gives you vision of an area.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 1,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'resistancePotion',
      name: 'RESISTANCE POTION',
      itemClass: 'potion',
      inventorySpace: 'consumable',
      action: 'DRINK',
      description: 'Gives you magic resistance.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 1,
      value: 100,
      enchant: 0,
    ),
    Item(
      icon: 'healingPotion',
      name: 'HEALING POTION',
      itemClass: 'potion',
      inventorySpace: 'consumable',
      action: 'DRINK',
      description: 'Close your wounds and heals you.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 1,
      value: 200,
      enchant: 0,
    ),
    Item(
      icon: 'magicRune',
      name: 'MAGIC RUNE',
      itemClass: 'magicRune',
      inventorySpace: 'consumable',
      action: 'ENCHANT',
      description: 'Enchants your gear.',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      uses: 1,
      value: 300,
      enchant: 0,
    ),
  ];
}
