import 'package:dsixv02app/models/gm/characterSkill.dart';

import 'character.dart';
import 'characterSkill.dart';
import 'characterSkillList.dart';
import 'package:dsixv02app/models/gm/location.dart';

class LocationList {
  CharacterSkillList skillList = CharacterSkillList();

  List<Location> locations = [
//MOUNTAIN
    Location(
      icon: 'mountain',
      name: 'Mountain',
      description: 'A mountain.',
      characters: [
        Character(
          icon: 'lizzard',
          image: 'undead',
          name: 'Lizzard',
          description: 'A lizzard.',
          baseHealth: 3,
          dice: 2,
          pDamage: 1,
          pArmor: 2,
          mDamage: 0,
          mArmor: 0,
          // pSkill: 2,
          // mSkill: 0,
          possibleSkills: [
            CharacterSkill(
              icon: 'poison',
              name: 'POISON',
              skillType: 'pSkill',
              description: 'Poison',
              value: 0,
            ),
            CharacterSkill(
              icon: 'dig',
              name: 'DIG',
              skillType: 'pSkill',
              description: 'Dig',
              value: 0,
            ),
            CharacterSkill(
              icon: 'hide',
              name: 'HIDE',
              skillType: 'pSkill',
              description: 'Hide',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fast',
              name: 'FAST',
              skillType: 'pSkill',
              description: 'Fast',
              value: 0,
            ),
            CharacterSkill(
              icon: 'thorn',
              name: 'THORN',
              skillType: 'pSkill',
              description: 'Thorn',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'climb',
              name: 'CLIMB',
              skillType: 'pSkill',
              description: 'Climb',
              value: 0,
            ),
          ],
          baseLoot: 0.25,
          baseXp: 25,
        ),
        Character(
          icon: 'bird',
          image: 'undead',
          name: 'Giant Bird',
          description: 'A giant bird.',
          baseHealth: 6,
          dice: 2,
          pDamage: 4,
          pArmor: 0,
          mDamage: 0,
          mArmor: 0,
          // pSkill: 1,
          // mSkill: 0,
          possibleSkills: [
            CharacterSkill(
              icon: 'bleed',
              name: 'BLEED',
              skillType: 'pSkill',
              description: 'Bleed',
              value: 0,
            ),
            CharacterSkill(
              icon: 'perceptive',
              name: 'PERCEPTIVE',
              skillType: 'pSkill',
              description: 'Perceptive',
              value: 0,
            ),
            CharacterSkill(
              icon: 'organized',
              name: 'ORGANIZED',
              skillType: 'pSkill',
              description: 'Organized',
              value: 0,
            ),
            CharacterSkill(
              icon: 'grab',
              name: 'GRAB',
              skillType: 'pSkill',
              description: 'Grab',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fast',
              name: 'FAST',
              skillType: 'pSkill',
              description: 'Fast',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fly',
              name: 'FLY',
              skillType: 'pSkill',
              description: 'Fly',
              value: 0,
            ),
          ],
          baseLoot: 0.25,
          baseXp: 25,
        ),
        Character(
          icon: 'dwarf',
          image: 'undead',
          name: 'Dwarf Miner',
          description: 'A dwarf miner.',
          baseHealth: 12,
          dice: 4,
          pDamage: 2,
          pArmor: 2,
          mDamage: 0,
          mArmor: 0,
          // pSkill: 2,
          // mSkill: 0,
          possibleSkills: [
            CharacterSkill(
              icon: 'build',
              name: 'BUILD',
              skillType: 'pSkill',
              description: 'Build',
              value: 0,
            ),
            CharacterSkill(
              icon: 'strategy',
              name: 'STRATEGY',
              skillType: 'pSkill',
              description: 'Strategy',
              value: 0,
            ),
            CharacterSkill(
              icon: 'organized',
              name: 'ORGANIZED',
              skillType: 'pSkill',
              description: 'Organized',
              value: 0,
            ),
            CharacterSkill(
              icon: 'climb',
              name: 'CLIMB',
              skillType: 'pSkill',
              description: 'Climb',
              value: 0,
            ),
            CharacterSkill(
              icon: 'explode',
              name: 'EXPLODE',
              skillType: 'pSkill',
              description: 'Explode',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'dig',
              name: 'DIG',
              skillType: 'pSkill',
              description: 'Dig',
              value: 0,
            ),
          ],
          baseLoot: 0.5,
          baseXp: 50,
        ),
        Character(
          icon: 'goblin',
          image: 'goblin',
          name: 'Goblin',
          description: 'A goblin.',
          baseHealth: 6,
          dice: 4,
          pDamage: 4,
          pArmor: 2,
          mDamage: 0,
          mArmor: 0,
          // pSkill: 2,
          // mSkill: 0,
          possibleSkills: [
            CharacterSkill(
              icon: 'strategy',
              name: 'STRATEGY',
              skillType: 'pSkill',
              description: 'Strategy',
              value: 0,
            ),
            CharacterSkill(
              icon: 'organized',
              name: 'ORGANIZED',
              skillType: 'pSkill',
              description: 'Organized',
              value: 0,
            ),
            CharacterSkill(
              icon: 'climb',
              name: 'CLIMB',
              skillType: 'pSkill',
              description: 'Climb',
              value: 0,
            ),
            CharacterSkill(
              icon: 'explode',
              name: 'EXPLODE',
              skillType: 'pSkill',
              description: 'Explode',
              value: 0,
            ),
            CharacterSkill(
              icon: 'dig',
              name: 'DIG',
              skillType: 'pSkill',
              description: 'Dig',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fly',
              name: 'FLY',
              skillType: 'pSkill',
              description: 'Fly',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'build',
              name: 'BUILD',
              skillType: 'pSkill',
              description: 'Build',
              value: 0,
            ),
          ],
          baseLoot: 0.5,
          baseXp: 50,
        ),
        Character(
          icon: 'goblin',
          image: 'goblin',
          name: 'Goblin Shaman',
          description: 'A goblin shaman.',
          baseHealth: 6,
          dice: 4,
          pDamage: 0,
          pArmor: 2,
          mDamage: 2,
          mArmor: 0,
          // pSkill: 1,
          // mSkill: 1,
          possibleSkills: [
            CharacterSkill(
              icon: 'climb',
              name: 'CLIMB',
              skillType: 'pSkill',
              description: 'Climb',
              value: 0,
            ),
            CharacterSkill(
              icon: 'strategy',
              name: 'STRATEGY',
              skillType: 'pSkill',
              description: 'Strategy',
              value: 0,
            ),
            CharacterSkill(
              icon: 'organized',
              name: 'ORGANIZED',
              skillType: 'pSkill',
              description: 'Organized',
              value: 0,
            ),
            CharacterSkill(
              icon: 'teleport',
              name: 'TELEPORT',
              skillType: 'mSkill',
              description: 'Teleport',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fear',
              name: 'FEAR',
              skillType: 'mSkill',
              description: 'Fear',
              value: 0,
            ),
            CharacterSkill(
              icon: 'heal',
              name: 'HEAL',
              description: 'Heal',
              value: 0,
            ),
            CharacterSkill(
              icon: 'spawn',
              name: 'SPAWN',
              skillType: 'mSkill',
              description: 'Spawn',
              value: 0,
            ),
            CharacterSkill(
              icon: 'illusion',
              name: 'ILLUSION',
              skillType: 'mSkill',
              description: 'Illusion',
              value: 0,
            ),
            CharacterSkill(
              icon: 'morph',
              name: 'MORPH',
              skillType: 'mSkill',
              description: 'Morph',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'mSkill',
              name: 'SPELL',
              skillType: 'mSkill',
              description: 'mSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'ritual',
              name: 'RITUAL',
              skillType: 'mSkill',
              description: 'Ritual',
              value: 0,
            ),
          ],
          baseLoot: 0.5,
          baseXp: 50,
        ),
        Character(
          icon: 'orc',
          image: 'orc',
          name: 'Orc Shaman',
          description: 'An orc shaman.',
          baseHealth: 15,
          dice: 6,
          pDamage: 0,
          pArmor: 3,
          mDamage: 3,
          mArmor: 0,
          // pSkill: 0,
          // mSkill: 1,
          possibleSkills: [
            CharacterSkill(
              icon: 'paralize',
              name: 'PARALIZE',
              skillType: 'mSkill',
              description: 'Paralize',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fear',
              name: 'FEAR',
              skillType: 'mSkill',
              description: 'Fear',
              value: 0,
            ),
            CharacterSkill(
              icon: 'heal',
              name: 'HEAL',
              description: 'Heal',
              value: 0,
            ),
            CharacterSkill(
              icon: 'spawn',
              name: 'SPAWN',
              skillType: 'mSkill',
              description: 'Spawn',
              value: 0,
            ),
            CharacterSkill(
              icon: 'seek',
              name: 'SEEK',
              skillType: 'mSkill',
              description: 'Seek',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'mSkill',
              name: 'SPELL',
              skillType: 'mSkill',
              description: 'mSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'drain',
              name: 'DRAIN',
              skillType: 'mSkill',
              description: 'Drain',
              value: 0,
            ),
          ],
          baseLoot: 1,
          baseXp: 100,
        ),
        Character(
          icon: 'orc',
          image: 'orc',
          name: 'Orc Berzerker',
          description: 'An orc berserker.',
          baseHealth: 18,
          dice: 6,
          pDamage: 8,
          pArmor: 0,
          mDamage: 0,
          mArmor: 0,
          // pSkill: 1,
          // mSkill: 0,
          possibleSkills: [
            CharacterSkill(
              icon: 'fast',
              name: 'FAST',
              skillType: 'pSkill',
              description: 'Fast',
              value: 0,
            ),
            CharacterSkill(
              icon: 'climb',
              name: 'CLIMB',
              skillType: 'pSkill',
              description: 'Climb',
              value: 0,
            ),
            CharacterSkill(
              icon: 'jump',
              name: 'JUMP',
              skillType: 'pSkill',
              description: 'Jump',
              value: 0,
            ),
            CharacterSkill(
              icon: 'grab',
              name: 'GRAB',
              skillType: 'pSkill',
              description: 'Grab',
              value: 0,
            ),
            CharacterSkill(
              icon: 'bleed',
              name: 'BLEED',
              skillType: 'pSkill',
              description: 'Bleed',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'strong',
              name: 'STRONG',
              skillType: 'pSkill',
              description: 'Strong',
              value: 0,
            ),
          ],
          baseLoot: 1,
          baseXp: 100,
        ),
        Character(
          icon: 'dwarf',
          image: 'undead',
          name: 'Dwarf Cleric',
          description: 'A dwarf cleric.',
          baseHealth: 15,
          dice: 6,
          pDamage: 0,
          pArmor: 7,
          mDamage: 1,
          mArmor: 0,
          // pSkill: 0,
          // mSkill: 1,
          possibleSkills: [
            CharacterSkill(
              icon: 'illusion',
              name: 'ILLUSION',
              skillType: 'mSkill',
              description: 'Illusion',
              value: 0,
            ),
            CharacterSkill(
              icon: 'paralize',
              name: 'PARALIZE',
              skillType: 'mSkill',
              description: 'Paralize',
              value: 0,
            ),
            CharacterSkill(
              icon: 'electric',
              name: 'ELECTRIC',
              skillType: 'mSkill',
              description: 'Electric',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fire',
              name: 'FIRE',
              skillType: 'mSkill',
              description: 'Fire',
              value: 0,
            ),
            CharacterSkill(
              icon: 'ice',
              name: 'ICE',
              skillType: 'mSkill',
              description: 'Ice',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'mSkill',
              name: 'SPELL',
              skillType: 'mSkill',
              description: 'mSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'heal',
              name: 'HEAL',
              skillType: 'mSkill',
              description: 'Heal',
              value: 0,
            ),
          ],
          baseLoot: 1,
          baseXp: 100,
        ),
        Character(
          icon: 'dwarf',
          image: 'undead',
          name: 'Dwarf Warrior',
          description: 'A dwarf warrior.',
          baseHealth: 15,
          dice: 6,
          pDamage: 3,
          pArmor: 6,
          mDamage: 0,
          mArmor: 0,
          // pSkill: 1,
          // mSkill: 0,
          possibleSkills: [
            CharacterSkill(
              icon: 'strategy',
              name: 'STRATEGY',
              skillType: 'pSkill',
              description: 'Strategy',
              value: 0,
            ),
            CharacterSkill(
              icon: 'push',
              name: 'PUSH',
              skillType: 'pSkill',
              description: 'Push',
              value: 0,
            ),
            CharacterSkill(
              icon: 'thorn',
              name: 'THORN',
              skillType: 'pSkill',
              description: 'Thorn',
              value: 0,
            ),
            CharacterSkill(
              icon: 'climb',
              name: 'CLIMB',
              skillType: 'pSkill',
              description: 'Climb',
              value: 0,
            ),
            CharacterSkill(
              icon: 'range',
              name: 'RANGE',
              skillType: 'pSkill',
              description: 'Range',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'organized',
              name: 'ORGANIZED',
              skillType: 'pSkill',
              description: 'Organized',
              value: 0,
            ),
          ],
          baseLoot: 1,
          baseXp: 100,
        ),
        Character(
          icon: 'earthElemental',
          image: 'undead',
          name: 'Earth Elemental',
          description: 'A rock elemental.',
          baseHealth: 21,
          dice: 8,
          pDamage: 0,
          pArmor: 5,
          mDamage: 0,
          mArmor: 3,
          // pSkill: 3,
          // mSkill: 0,
          possibleSkills: [
            CharacterSkill(
              icon: 'grab',
              name: 'GRAB',
              skillType: 'pSkill',
              description: 'Grab',
              value: 0,
            ),
            CharacterSkill(
              icon: 'pull',
              name: 'PULL',
              skillType: 'pSkill',
              description: 'Pull',
              value: 0,
            ),
            CharacterSkill(
              icon: 'spin',
              name: 'SPIN',
              skillType: 'pSkill',
              description: 'Spin',
              value: 0,
            ),
            CharacterSkill(
              icon: 'push',
              name: 'PUSH',
              skillType: 'pSkill',
              description: 'Push',
              value: 0,
            ),
            CharacterSkill(
              icon: 'thorn',
              name: 'THORN',
              skillType: 'pSkill',
              description: 'Thorn',
              value: 0,
            ),
            CharacterSkill(
              icon: 'climb',
              name: 'CLIMB',
              skillType: 'pSkill',
              description: 'Climb',
              value: 0,
            ),
            CharacterSkill(
              icon: 'combine',
              name: 'COMBINE',
              skillType: 'pSkill',
              description: 'Combine',
              value: 0,
            ),
            CharacterSkill(
              icon: 'split',
              name: 'SPLIT',
              skillType: 'pSkill',
              description: 'Split',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'camouflage',
              name: 'CAMOUFLAGE',
              skillType: 'pSkill',
              description: 'Hide',
              value: 0,
            ),
          ],
          baseLoot: 1.5,
          baseXp: 150,
        ),
        Character(
          icon: 'dragon',
          image: 'undead',
          name: 'Baby Dragon',
          description: 'A baby dragon.',
          baseHealth: 24,
          dice: 8,
          pDamage: 3,
          pArmor: 3,
          mDamage: 2,
          mArmor: 2,
          // pSkill: 1,
          // mSkill: 0,
          possibleSkills: [
            CharacterSkill(
              icon: 'jump',
              name: 'JUMP',
              skillType: 'pSkill',
              description: 'Jump',
              value: 0,
            ),
            CharacterSkill(
              icon: 'climb',
              name: 'CLIMB',
              skillType: 'pSkill',
              description: 'Climb',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fast',
              name: 'FAST',
              skillType: 'pSkill',
              description: 'Fast',
              value: 0,
            ),
            CharacterSkill(
              icon: 'camouflage',
              name: 'CAMOUFLAGE',
              skillType: 'pSkill',
              description: 'Camouflage',
              value: 0,
            ),
            CharacterSkill(
              icon: 'poison',
              name: 'POISON',
              skillType: 'pSkill',
              description: 'Poison',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'perceptive',
              name: 'PERCEPTIVE',
              skillType: 'pSkill',
              description: 'Perceptive',
              value: 0,
            ),
          ],
          baseLoot: 1.5,
          baseXp: 150,
        ),
        Character(
          icon: 'ogre',
          image: 'ogre',
          name: 'Ogre',
          description: 'An ogre.',
          baseHealth: 60,
          dice: 10,
          pDamage: 10,
          pArmor: 0,
          mDamage: 0,
          mArmor: 0,
          // pSkill: 1,
          // mSkill: 0,
          possibleSkills: [
            CharacterSkill(
              icon: 'charge',
              name: 'CHARGE',
              skillType: 'pSkill',
              description: 'Charge',
              value: 0,
            ),
            CharacterSkill(
              icon: 'grab',
              name: 'GRAB',
              skillType: 'pSkill',
              description: 'Grab',
              value: 0,
            ),
            CharacterSkill(
              icon: 'throw',
              name: 'THROW',
              skillType: 'pSkill',
              description: '',
              value: 0,
            ),
            CharacterSkill(
              icon: 'swallow',
              name: 'SWALLOW',
              skillType: 'pSkill',
              description: 'Swallow',
              value: 0,
            ),
            CharacterSkill(
              icon: 'climb',
              name: 'CLIMB',
              skillType: 'pSkill',
              description: 'Climb',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'strong',
              name: 'STRONG',
              skillType: 'pSkill',
              description: 'Strong',
              value: 0,
            ),
          ],
          baseLoot: 2,
          baseXp: 200,
        ),
      ],
    ),

//SWAMP
    Location(
      icon: 'swamp',
      name: 'Swamp',
      description: 'A swamp.',
      characters: [
        Character(
          icon: 'zombie',
          image: 'undead',
          name: 'Zombie',
          description: 'A zombie.',
          baseHealth: 9,
          dice: 2,
          pDamage: 2,
          pArmor: 1,
          mDamage: 0,
          mArmor: 0,
          possibleSkills: [
            CharacterSkill(
              icon: 'grab',
              name: 'GRAB',
              skillType: 'pSkill',
              description: 'Grab',
              value: 0,
            ),
            CharacterSkill(
              icon: 'dig',
              name: 'DIG',
              skillType: 'pSkill',
              description: 'Dig',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fast',
              name: 'FAST',
              skillType: 'pSkill',
              description: 'Fast',
              value: 0,
            ),
            CharacterSkill(
              icon: 'climb',
              name: 'CLIMB',
              skillType: 'pSkill',
              description: 'Climb',
              value: 0,
            ),
            CharacterSkill(
              icon: 'explode',
              name: 'EXPLODE',
              skillType: 'pSkill',
              description: 'Explode',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'disease',
              name: 'DISEASE',
              skillType: 'pSkill',
              description: 'Disease',
              value: 0,
            ),
          ],
          baseLoot: 0.25,
          baseXp: 25,
        ),
        Character(
          icon: 'undead',
          image: 'undead',
          name: 'Skeleton',
          description: 'A skeleton.',
          baseHealth: 3,
          dice: 2,
          pDamage: 3,
          pArmor: 2,
          mDamage: 0,
          mArmor: 0,
          possibleSkills: [
            CharacterSkill(
              icon: 'split',
              name: 'SPLIT',
              skillType: 'pSkill',
              description: 'Split',
              value: 0,
            ),
            CharacterSkill(
              icon: 'combine',
              name: 'COMBINE',
              skillType: 'pSkill',
              description: 'Combine',
              value: 0,
            ),
            CharacterSkill(
              icon: 'swim',
              name: 'SWIM',
              skillType: 'pSkill',
              description: 'Swim',
              value: 0,
            ),
            CharacterSkill(
              icon: 'range',
              name: 'RANGE',
              skillType: 'pSkill',
              description: 'Range',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fast',
              name: 'FAST',
              skillType: 'pSkill',
              description: 'Fast',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'camouflage',
              name: 'CAMOUFLAGE',
              skillType: 'pSkill',
              description: 'Hide',
              value: 0,
            ),
          ],
          baseLoot: 0.25,
          baseXp: 25,
        ),
        Character(
          icon: 'giantFrog',
          image: 'undead',
          name: 'Giant Frog',
          description: 'A giant frog.',
          baseHealth: 12,
          dice: 2,
          pDamage: 0,
          pArmor: 0,
          mDamage: 0,
          mArmor: 0,
          possibleSkills: [
            CharacterSkill(
              icon: 'pull',
              name: 'PULL',
              skillType: 'pSkill',
              description: 'Pull',
              value: 0,
            ),
            CharacterSkill(
              icon: 'swallow',
              name: 'SWALLOW',
              skillType: 'pSkill',
              description: 'Swallow',
              value: 0,
            ),
            CharacterSkill(
              icon: 'swim',
              name: 'SWIM',
              skillType: 'pSkill',
              description: 'Swim',
              value: 0,
            ),
            CharacterSkill(
              icon: 'climb',
              name: 'CLIMB',
              skillType: 'pSkill',
              description: 'Climb',
              value: 0,
            ),
            CharacterSkill(
              icon: 'poison',
              name: 'POISON',
              skillType: 'pSkill',
              description: 'Poison',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'jump',
              name: 'JUMP',
              skillType: 'pSkill',
              description: 'Jump',
              value: 0,
            ),
          ],
          baseLoot: 0.25,
          baseXp: 25,
        ),
        Character(
          icon: 'ghost',
          image: 'undead',
          name: 'Ghost',
          description: 'A ghost.',
          baseHealth: 3,
          dice: 2,
          pDamage: 0,
          pArmor: 0,
          mDamage: 2,
          mArmor: 0,
          // pSkill: 0,
          // mSkill: 1,
          possibleSkills: [
            CharacterSkill(
              icon: 'levitate',
              name: 'LEVITATE',
              skillType: 'mSkill',
              description: 'Levitate',
              value: 0,
            ),
            CharacterSkill(
              icon: 'ignore',
              name: 'IGNORE',
              skillType: 'mSkill',
              description: 'Ignore',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fear',
              name: 'FEAR',
              skillType: 'mSkill',
              description: 'Fear',
              value: 0,
            ),
            CharacterSkill(
              icon: 'paralize',
              name: 'PARALIZE',
              skillType: 'mSkill',
              description: 'Paralize',
              value: 0,
            ),
            CharacterSkill(
              icon: 'teleport',
              name: 'TELEPORT',
              skillType: 'mSkill',
              description: 'Teleport',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'mSkill',
              name: 'SPELL',
              skillType: 'mSkill',
              description: 'mSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'ethereal',
              name: 'ETHEREAL',
              skillType: 'mSkill',
              description: 'Ethereal',
              value: 0,
            ),
          ],
          baseLoot: 0.25,
          baseXp: 25,
        ),
        Character(
          icon: 'giantBat',
          image: 'undead',
          name: 'Giant Bat',
          description: 'A giant bat.',
          baseHealth: 6,
          dice: 4,
          pDamage: 4,
          pArmor: 2,
          mDamage: 0,
          mArmor: 0,
          possibleSkills: [
            CharacterSkill(
              icon: 'climb',
              name: 'CLIMB',
              skillType: 'pSkill',
              description: 'Climb',
              value: 0,
            ),
            CharacterSkill(
              icon: 'bleed',
              name: 'BLEED',
              skillType: 'pSkill',
              description: 'Bleed',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fly',
              name: 'FLY',
              skillType: 'pSkill',
              description: 'Fly',
              value: 0,
            ),
            CharacterSkill(
              icon: 'disease',
              name: 'DISEASE',
              skillType: 'pSkill',
              description: 'Disease',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fast',
              name: 'FAST',
              skillType: 'pSkill',
              description: 'Fast',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'perceptive',
              name: 'PERCEPTIVE',
              skillType: 'pSkill',
              description: 'Perceptive',
              value: 0,
            ),
          ],
          baseLoot: 0.5,
          baseXp: 50,
        ),
        Character(
          icon: 'skeletonMage',
          image: 'undead',
          name: 'Skeleton Mage',
          description: 'A skeleton mage.',
          baseHealth: 6,
          dice: 4,
          pDamage: 0,
          pArmor: 2,
          mDamage: 3,
          mArmor: 0,
          // pSkill: 0,
          // mSkill: 1,
          possibleSkills: [
            CharacterSkill(
              icon: 'electric',
              name: 'ELECTRIC',
              skillType: 'mSkill',
              description: 'Electric',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fire',
              name: 'FIRE',
              skillType: 'mSkill',
              description: 'Fire',
              value: 0,
            ),
            CharacterSkill(
              icon: 'ice',
              name: 'ICE',
              skillType: 'mSkill',
              description: 'Ice',
              value: 0,
            ),
            CharacterSkill(
              icon: 'seek',
              name: 'SEEK',
              skillType: 'mSkill',
              description: 'Seek',
              value: 0,
            ),
            CharacterSkill(
              icon: 'spawn',
              name: 'SPAWN',
              skillType: 'pSkill',
              description: 'Spawn',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'mSkill',
              name: 'SPELL',
              skillType: 'mSkill',
              description: 'mSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'ritual',
              name: 'RITUAL',
              skillType: 'mSkill',
              description: 'Ritual',
              value: 0,
            ),
          ],
          baseLoot: 0.5,
          baseXp: 50,
        ),
        Character(
          icon: 'crocodile',
          image: 'undead',
          name: 'Crocodile',
          description: 'A crocodile.',
          baseHealth: 12,
          dice: 6,
          pDamage: 6,
          pArmor: 4,
          mDamage: 0,
          mArmor: 0,
          // pSkill: 1,
          // mSkill: 0,
          possibleSkills: [
            CharacterSkill(
              icon: 'camouflage',
              name: 'CAMOUFLAGE',
              skillType: 'pSkill',
              description: 'Hide',
              value: 0,
            ),
            CharacterSkill(
              icon: 'grab',
              name: 'GRAB',
              skillType: 'pSkill',
              description: 'Grab',
              value: 0,
            ),
            CharacterSkill(
              icon: 'strong',
              name: 'STRONG',
              skillType: 'pSkill',
              description: 'Strong',
              value: 0,
            ),
            CharacterSkill(
              icon: 'bleed',
              name: 'BLEED',
              skillType: 'pSkill',
              description: 'Bleed',
              value: 0,
            ),
            CharacterSkill(
              icon: 'spin',
              name: 'SPIN',
              skillType: 'pSkill',
              description: 'Spin',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'swim',
              name: 'SWIM',
              skillType: 'pSkill',
              description: 'Swim',
              value: 0,
            ),
          ],
          baseLoot: 1,
          baseXp: 100,
        ),
        Character(
          icon: 'giantSnake',
          image: 'undead',
          name: 'Giant Snake',
          description: 'A giant snake.',
          baseHealth: 12,
          dice: 6,
          pDamage: 4,
          pArmor: 2,
          mDamage: 0,
          mArmor: 1,
          // pSkill: 2,
          // mSkill: 0,
          possibleSkills: [
            CharacterSkill(
              icon: 'swim',
              name: 'SWIM',
              skillType: 'pSkill',
              description: 'Swim',
              value: 0,
            ),
            CharacterSkill(
              icon: 'jump',
              name: 'JUMP',
              skillType: 'pSkill',
              description: 'Jump',
              value: 0,
            ),
            CharacterSkill(
              icon: 'grab',
              name: 'GRAB',
              skillType: 'pSkill',
              description: 'Grab',
              value: 0,
            ),
            CharacterSkill(
              icon: 'climb',
              name: 'CLIMB',
              skillType: 'pSkill',
              description: 'Climb',
              value: 0,
            ),
            CharacterSkill(
              icon: 'swallow',
              name: 'SWALLOW',
              skillType: 'pSkill',
              description: 'Swallow',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fast',
              name: 'FAST',
              skillType: 'pSkill',
              description: 'Fast',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'poison',
              name: 'POISON',
              skillType: 'pSkill',
              description: 'Poison',
              value: 0,
            ),
          ],
          baseLoot: 1,
          baseXp: 100,
        ),
        Character(
          icon: 'giantCrab',
          image: 'undead',
          name: 'Giant Crab',
          description: 'A giant crab.',
          baseHealth: 9,
          dice: 6,
          pDamage: 3,
          pArmor: 6,
          mDamage: 0,
          mArmor: 0,
          // pSkill: 2,
          // mSkill: 0,
          possibleSkills: [
            CharacterSkill(
              icon: 'grab',
              name: 'GRAB',
              skillType: 'pSkill',
              description: 'Grab',
              value: 0,
            ),
            CharacterSkill(
              icon: 'climb',
              name: 'CLIMB',
              skillType: 'pSkill',
              description: 'Climb',
              value: 0,
            ),
            CharacterSkill(
              icon: 'swim',
              name: 'SWIM',
              skillType: 'pSkill',
              description: 'Swim',
              value: 0,
            ),
            CharacterSkill(
              icon: 'bleed',
              name: 'BLEED',
              skillType: 'pSkill',
              description: 'Bleed',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fast',
              name: 'FAST',
              skillType: 'pSkill',
              description: 'Fast',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'dig',
              name: 'DIG',
              skillType: 'pSkill',
              description: 'Dig',
              value: 0,
            ),
          ],
          baseLoot: 1,
          baseXp: 100,
        ),
        Character(
          icon: 'vampire',
          image: 'undead',
          name: 'Vampire',
          description: 'A vampire.',
          baseHealth: 9,
          dice: 6,
          pDamage: 3,
          pArmor: 2,
          mDamage: 2,
          mArmor: 0,
          // pSkill: 1,
          // mSkill: 1,
          possibleSkills: [
            CharacterSkill(
              icon: 'morph',
              name: 'MORPH',
              skillType: 'mSkill',
              description: 'Morph',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fly',
              name: 'FLY',
              skillType: 'pSkill',
              description: 'Fly',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fear',
              name: 'FEAR',
              skillType: 'mSkill',
              description: 'Fear',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fast',
              name: 'FAST',
              skillType: 'pSkill',
              description: 'Fast',
              value: 0,
            ),
            CharacterSkill(
              icon: 'strong',
              name: 'STRONG',
              skillType: 'pSkill',
              description: 'Strong',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'mSkill',
              name: 'SPELL',
              skillType: 'mSkill',
              description: 'mSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'drain',
              name: 'DRAIN',
              skillType: 'mSkill',
              description: 'Drain',
              value: 0,
            ),
          ],
          baseLoot: 1,
          baseXp: 100,
        ),
        Character(
          icon: 'necromancer',
          image: 'undead',
          name: 'Necromancer',
          description: 'A necromancer.',
          baseHealth: 18,
          dice: 8,
          pDamage: 0,
          pArmor: 0,
          mDamage: 4,
          mArmor: 2,
          // pSkill: 0,
          // mSkill: 3,
          possibleSkills: [
            CharacterSkill(
              icon: 'charm',
              name: 'CHARM',
              skillType: 'mSkill',
              description: 'Charm',
              value: 0,
            ),
            CharacterSkill(
              icon: 'ritual',
              name: 'RITUAL',
              skillType: 'mSkill',
              description: 'Ritual',
              value: 0,
            ),
            CharacterSkill(
              icon: 'illusion',
              name: 'ILLUSION',
              skillType: 'mSkill',
              description: 'Illusion',
              value: 0,
            ),
            CharacterSkill(
              icon: 'seek',
              name: 'SEEK',
              skillType: 'mSkill',
              description: 'Seek',
              value: 0,
            ),
            CharacterSkill(
              icon: 'smart',
              name: 'SMART',
              skillType: 'mSkill',
              description: 'Smart',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'mSkill',
              name: 'SPELL',
              skillType: 'mSkill',
              description: 'mSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'mSkill',
              name: 'SPELL',
              skillType: 'mSkill',
              description: 'mSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'mSkill',
              name: 'SPELL',
              skillType: 'mSkill',
              description: 'mSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'spawn',
              name: 'SPAWN',
              skillType: 'pSkill',
              description: 'Spawn',
              value: 0,
            ),
          ],
          baseLoot: 1.5,
          baseXp: 150,
        ),
        Character(
          icon: 'golen',
          image: 'undead',
          name: 'Golen',
          description: 'A rock elemental.',
          baseHealth: 30,
          dice: 8,
          pDamage: 0,
          pArmor: 4,
          mDamage: 3,
          mArmor: 0,
          // pSkill: 1,
          // mSkill: 1,
          possibleSkills: [
            CharacterSkill(
              icon: 'ice',
              name: 'ICE',
              skillType: 'mSkill',
              description: 'Ice',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fire',
              name: 'FIRE',
              skillType: 'mSkill',
              description: 'Fire',
              value: 0,
            ),
            CharacterSkill(
              icon: 'electric',
              name: 'ELECTRIC',
              skillType: 'mSkill',
              description: 'Electric',
              value: 0,
            ),
            CharacterSkill(
              icon: 'spin',
              name: 'SPIN',
              skillType: 'pSkill',
              description: 'Spin',
              value: 0,
            ),
            CharacterSkill(
              icon: 'regenerate',
              name: 'REGENERATE',
              skillType: 'pSkill',
              description: 'Regenerate',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'mSkill',
              name: 'SPELL',
              skillType: 'mSkill',
              description: 'mSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'explode',
              name: 'EXPLODE',
              skillType: 'pSkill',
              description: 'Explode',
              value: 0,
            ),
          ],
          baseLoot: 1.5,
          baseXp: 150,
        ),
        Character(
          icon: 'ancientVampire',
          image: 'undead',
          name: 'Ancient Vampire',
          description: 'An ancient vampire.',
          baseHealth: 24,
          dice: 10,
          pDamage: 5,
          pArmor: 5,
          mDamage: 5,
          mArmor: 4,
          // pSkill: 1,
          // mSkill: 0,
          possibleSkills: [
            CharacterSkill(
              icon: 'morph',
              name: 'MORPH',
              skillType: 'mSkill',
              description: 'Morph',
              value: 0,
            ),
            CharacterSkill(
              icon: 'drain',
              name: 'DRAIN',
              skillType: 'mSkill',
              description: 'Drain',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fear',
              name: 'FEAR',
              skillType: 'mSkill',
              description: 'Fear',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fast',
              name: 'FAST',
              skillType: 'pSkill',
              description: 'Fast',
              value: 0,
            ),
            CharacterSkill(
              icon: 'strong',
              name: 'STRONG',
              skillType: 'pSkill',
              description: 'Strong',
              value: 0,
            ),
            CharacterSkill(
              icon: 'bleed',
              name: 'BLEED',
              skillType: 'pSkill',
              description: 'Bleed',
              value: 0,
            ),
            CharacterSkill(
              icon: 'paralize',
              name: 'PARALIZE',
              skillType: 'mSkill',
              description: 'Paralize',
              value: 0,
            ),
          ],
          selectedSkills: [
            CharacterSkill(
              icon: 'pSkill',
              name: 'ABILITY',
              skillType: 'pSkill',
              description: 'pSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'mSkill',
              name: 'SPELL',
              skillType: 'mSkill',
              description: 'mSkill',
              value: 0,
            ),
            CharacterSkill(
              icon: 'fly',
              name: 'FLY',
              skillType: 'pSkill',
              description: 'Fly',
              value: 0,
            ),
          ],
          baseLoot: 2,
          baseXp: 200,
        ),
      ],
    ),
  ];

  LocationList();
}
