import 'npc.dart';

class NpcTypeList {
  List<Npc> npcType = [
    Npc(
      icon: 'undead',
      image: 'undead',
      name: 'SKELETON MAGE',
      description: 'Skely pew pew',
      baseHealth: 3,
      dice: 2,
      pDamage: 0,
      pArmor: 3,
      mDamage: 2,
      mArmor: 0,
      pSkill: 0,
      mSkill: 1,
      baseLoot: 0.25,
      baseXp: 25,
    ),
    Npc(
      icon: 'undead',
      image: 'undead',
      name: 'SKELETON',
      description: 'swaordsnd hff ds',
      baseHealth: 3,
      dice: 2,
      pDamage: 2,
      pArmor: 3,
      mDamage: 0,
      mArmor: 0,
      pSkill: 1,
      mSkill: 0,
      baseLoot: 0.25,
      baseXp: 25,
    ),
    Npc(
      icon: 'undead',
      image: 'undead',
      name: 'ZOMBIE',
      description: 'Brainsinasin  asd',
      baseHealth: 6,
      dice: 2,
      pDamage: 1,
      pArmor: 2,
      mDamage: 0,
      mArmor: 1,
      pSkill: 1,
      mSkill: 0,
      baseLoot: 0.25,
      baseXp: 25,
    ),
    Npc(
      icon: 'halfling',
      image: 'halfling',
      name: 'HALFLING SCOUT',
      description: 'Brainsinasin  asd',
      baseHealth: 6,
      dice: 4,
      pDamage: 3,
      pArmor: 3,
      mDamage: 0,
      mArmor: 0,
      pSkill: 2,
      mSkill: 0,
      baseLoot: 0.5,
      baseXp: 50,
    ),
    Npc(
      icon: 'halfling',
      image: 'halfling',
      name: 'HALFLING MUSICIAN',
      description: 'Brainsinasin  asd',
      baseHealth: 6,
      dice: 4,
      pDamage: 2,
      pArmor: 2,
      mDamage: 0,
      mArmor: 2,
      pSkill: 1,
      mSkill: 1,
      baseLoot: 0.5,
      baseXp: 50,
    ),
    Npc(
      icon: 'halfling',
      image: 'halfling',
      name: 'HALFLING WIZZARD',
      description: 'Brainsinasin  asd',
      baseHealth: 6,
      dice: 4,
      pDamage: 0,
      pArmor: 0,
      mDamage: 3,
      mArmor: 3,
      pSkill: 0,
      mSkill: 2,
      baseLoot: 0.5,
      baseXp: 50,
    ),
    Npc(
      icon: 'goblin',
      image: 'goblin',
      name: 'GOBLIN WARRIOR',
      description: 'Brainsinasin  asd',
      baseHealth: 6,
      dice: 4,
      pDamage: 4,
      pArmor: 2,
      mDamage: 0,
      mArmor: 0,
      pSkill: 2,
      mSkill: 0,
      baseLoot: 0.5,
      baseXp: 50,
    ),
    Npc(
      icon: 'goblin',
      image: 'goblin',
      name: 'GOBLIN SHAMAN',
      description: 'Brainsinasin  asd',
      baseHealth: 6,
      dice: 4,
      pDamage: 0,
      pArmor: 2,
      mDamage: 4,
      mArmor: 0,
      pSkill: 1,
      mSkill: 1,
      baseLoot: 0.5,
      baseXp: 50,
    ),
    Npc(
      icon: 'human',
      image: 'goblin',
      name: 'HUMAN WARRIOR',
      description: 'Brainsinasin  asd',
      baseHealth: 12,
      dice: 6,
      pDamage: 4,
      pArmor: 2,
      mDamage: 0,
      mArmor: 0,
      pSkill: 2,
      mSkill: 0,
      baseLoot: 1,
      baseXp: 100,
    ),
    Npc(
      icon: 'human',
      image: 'goblin',
      name: 'HUMAN WIZZARD',
      description: 'Brainsinasin  asd',
      baseHealth: 12,
      dice: 6,
      pDamage: 0,
      pArmor: 0,
      mDamage: 4,
      mArmor: 4,
      pSkill: 0,
      mSkill: 2,
      baseLoot: 1,
      baseXp: 100,
    ),
    Npc(
      icon: 'elf',
      image: 'goblin',
      name: 'ELF WARRIOR',
      description: 'Brainsinasin  asd',
      baseHealth: 9,
      dice: 6,
      pDamage: 4,
      pArmor: 3,
      mDamage: 0,
      mArmor: 2,
      pSkill: 2,
      mSkill: 0,
      baseLoot: 1,
      baseXp: 100,
    ),
    Npc(
      icon: 'elf',
      image: 'goblin',
      name: 'ELF WIZZARD',
      description: 'Brainsinasin  asd',
      baseHealth: 9,
      dice: 6,
      pDamage: 0,
      pArmor: 2,
      mDamage: 4,
      mArmor: 3,
      pSkill: 1,
      mSkill: 1,
      baseLoot: 1,
      baseXp: 100,
    ),
    Npc(
      icon: 'dwarf',
      image: 'goblin',
      name: 'DWARF WARRIOR',
      description: 'Brainsinasin  asd',
      baseHealth: 15,
      dice: 6,
      pDamage: 3,
      pArmor: 6,
      mDamage: 0,
      mArmor: 0,
      pSkill: 1,
      mSkill: 0,
      baseLoot: 1,
      baseXp: 100,
    ),
    Npc(
      icon: 'dwarf',
      image: 'goblin',
      name: 'DWARF CLERIC',
      description: 'Brainsinasin  asd',
      baseHealth: 15,
      dice: 6,
      pDamage: 0,
      pArmor: 6,
      mDamage: 3,
      mArmor: 0,
      pSkill: 0,
      mSkill: 1,
      baseLoot: 1,
      baseXp: 100,
    ),
    Npc(
      icon: 'orc',
      image: 'orc',
      name: 'ORC BERSERKER',
      description: 'Brainsinasin  asd',
      baseHealth: 18,
      dice: 6,
      pDamage: 8,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      pSkill: 1,
      mSkill: 0,
      baseLoot: 1,
      baseXp: 100,
    ),
    Npc(
      icon: 'orc',
      image: 'orc',
      name: 'ORC FIGHTER',
      description: 'Brainsinasin  asd',
      baseHealth: 15,
      dice: 6,
      pDamage: 5,
      pArmor: 4,
      mDamage: 0,
      mArmor: 0,
      pSkill: 1,
      mSkill: 0,
      baseLoot: 1,
      baseXp: 100,
    ),
    Npc(
      icon: 'orc',
      image: 'orc',
      name: 'ORC SHAMAN',
      description: 'Brainsinasin  asd',
      baseHealth: 15,
      dice: 6,
      pDamage: 0,
      pArmor: 3,
      mDamage: 4,
      mArmor: 2,
      pSkill: 0,
      mSkill: 1,
      baseLoot: 1,
      baseXp: 100,
    ),
    Npc(
      icon: 'ogre',
      image: 'ogre',
      name: 'OGRE RAIDER',
      description: 'Brainsinasin  asd',
      baseHealth: 60,
      dice: 10,
      pDamage: 8,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      pSkill: 2,
      mSkill: 0,
      baseLoot: 2,
      baseXp: 200,
    ),
    Npc(
      icon: 'minotaur',
      image: 'goblin',
      name: 'MINOTAUR',
      description: 'Brainsinasin  asd',
      baseHealth: 45,
      dice: 10,
      pDamage: 5,
      pArmor: 3,
      mDamage: 0,
      mArmor: 3,
      pSkill: 2,
      mSkill: 1,
      baseLoot: 2,
      baseXp: 200,
    ),
  ];

  NpcTypeList();
}
