import 'storySettings.dart';

List<StorySettings> settingsList = [
  StorySettings(
    icon: 'veryEasy',
    name: 'VERY EASY',
    description: 'Very easy.',
    numberOfQuests: 3,
    questXp: 25,
    totalXp: 25,
    questGold: 200,
    totalGold: 200,
  ),
  StorySettings(
    icon: 'easy',
    name: 'EASY',
    description: 'Easy.',
    numberOfQuests: 3,
    questXp: 50,
    totalXp: 50,
    questGold: 200,
    totalGold: 200,
  ),
  StorySettings(
    icon: 'normal',
    name: 'NORMAL',
    description: 'Normal.',
    numberOfQuests: 3,
    questXp: 50,
    totalXp: 50,
    questGold: 100,
    totalGold: 100,
  ),
  StorySettings(
    icon: 'hard',
    name: 'HARD',
    description: 'Hard.',
    numberOfQuests: 3,
    questXp: 100,
    totalXp: 100,
    questGold: 100,
    totalGold: 100,
  ),
  StorySettings(
    icon: 'epic',
    name: 'EPIC',
    description: 'Very hard.',
    numberOfQuests: 3,
    questXp: 150,
    totalXp: 150,
    questGold: 300,
    totalGold: 300,
  ),
];
