import 'package:dsixv02app/shared/app_Icons.dart';
import 'dart:math';
import 'item.dart';

class Shop {
  Item randomItem() {
    Item? newItem;
    int? randomItem;
    switch (randomCategory()) {
      case 'lightWeapons':
        randomItem = Random().nextInt(this.lightWeapons.length);
        newItem = lightWeapons[randomItem];
        break;
      case 'heavyWeapons':
        randomItem = Random().nextInt(this.heavyWeapons.length);
        newItem = heavyWeapons[randomItem];
        break;
      case 'rangedWeapons':
        randomItem = Random().nextInt(this.rangedWeapons.length);
        newItem = rangedWeapons[randomItem];
        break;
      case 'magicWeapons':
        randomItem = Random().nextInt(this.magicWeapons.length);
        newItem = magicWeapons[randomItem];
        break;
      case 'armor':
        randomItem = Random().nextInt(this.armor.length);
        newItem = armor[randomItem];
        break;
      case 'ancient':
        randomItem = Random().nextInt(this.ancient.length);
        newItem = ancient[randomItem];
        break;
      case 'consumable':
        randomItem = Random().nextInt(this.consumable.length);
        newItem = consumable[randomItem];
        break;
    }
    return newItem!;
  }

  String randomCategory() {
    List<String> category = [
      'lightWeapons',
      'heavyWeapons',
      'rangedWeapons',
      'magicWeapons',
      'armor',
      'ancient',
      'consumable',
    ];
    int randomCategory = Random().nextInt(category.length);
    return category[randomCategory];
  }

  List<Item> lightWeapons = [
    Item(
      icon: AppIcons.baton,
      name: 'baton',
      itemSlot: 'oneHand',
      type: 'melee',
      pDamage: 0,
      pArmor: 1,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      value: 100,
      maxWeaponRange: 5,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.dagger,
      name: 'dagger',
      itemSlot: 'oneHand',
      type: 'melee',
      pDamage: 1,
      mDamage: 0,
      pArmor: 0,
      mArmor: 0,
      weight: 1,
      value: 100,
      maxWeaponRange: 5,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.mace,
      name: 'mace',
      itemSlot: 'oneHand',
      type: 'melee',
      pDamage: 2,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 3,
      value: 100,
      maxWeaponRange: 10,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.claw,
      name: 'claw',
      itemSlot: 'oneHand',
      type: 'melee',
      pDamage: 1,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      value: 200,
      maxWeaponRange: 5,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.axe,
      name: 'axe',
      itemSlot: 'oneHand',
      type: 'melee',
      pDamage: 2,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 2,
      value: 200,
      maxWeaponRange: 10,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.shortSword,
      name: 'short sword',
      itemSlot: 'oneHand',
      type: 'melee',
      pDamage: 1,
      pArmor: 1,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      value: 300,
      maxWeaponRange: 10,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.ritualDagger,
      name: 'ritual dagger',
      itemSlot: 'oneHand',
      type: 'melee',
      pDamage: 1,
      pArmor: 0,
      mDamage: 1,
      mArmor: 0,
      weight: 2,
      value: 300,
      maxWeaponRange: 10,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.shortSpear,
      name: 'short spear',
      itemSlot: 'oneHand',
      type: 'melee',
      pDamage: 2,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      value: 300,
      maxWeaponRange: 15,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.rapier,
      name: 'rapier',
      itemSlot: 'oneHand',
      type: 'melee',
      pDamage: 3,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 2,
      value: 400,
      maxWeaponRange: 10,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.sword,
      name: 'sword',
      itemSlot: 'oneHand',
      type: 'melee',
      pDamage: 2,
      pArmor: 2,
      mDamage: 0,
      mArmor: 0,
      weight: 4,
      value: 400,
      maxWeaponRange: 10,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.magicSword,
      name: 'magic sword',
      itemSlot: 'oneHand',
      type: 'melee',
      pDamage: 1,
      pArmor: 1,
      mDamage: 1,
      mArmor: 0,
      weight: 3,
      value: 400,
      maxWeaponRange: 15,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.morningStar,
      name: 'morningStar',
      itemSlot: 'oneHand',
      type: 'melee',
      pDamage: 5,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 6,
      value: 400,
      maxWeaponRange: 10,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.saber,
      name: 'saber',
      itemSlot: 'oneHand',
      type: 'melee',
      pDamage: 4,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 3,
      value: 500,
      maxWeaponRange: 10,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.longSword,
      name: 'long sword',
      itemSlot: 'oneHand',
      type: 'melee',
      pDamage: 3,
      pArmor: 2,
      mDamage: 0,
      mArmor: 0,
      weight: 5,
      value: 500,
      maxWeaponRange: 15,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.magicAxe,
      name: 'magic axe',
      itemSlot: 'oneHand',
      type: 'melee',
      pDamage: 2,
      pArmor: 0,
      mDamage: 2,
      mArmor: 0,
      weight: 4,
      value: 600,
      maxWeaponRange: 10,
      minWeaponRange: 0,
    ),
  ];

  List<Item> heavyWeapons = [
    Item(
      icon: AppIcons.longSpear,
      name: 'long spear',
      itemSlot: 'twoHands',
      type: 'melee',
      pDamage: 3,
      mDamage: 0,
      pArmor: 0,
      mArmor: 0,
      weight: 2,
      value: 300,
      maxWeaponRange: 30,
      minWeaponRange: 40,
    ),
    Item(
      icon: AppIcons.quarterstaff,
      name: 'quarterstaff',
      itemSlot: 'twoHands',
      type: 'melee',
      pDamage: 1,
      pArmor: 3,
      mDamage: 0,
      mArmor: 0,
      weight: 4,
      value: 300,
      maxWeaponRange: 20,
      minWeaponRange: 30,
    ),
    Item(
      icon: AppIcons.doubleSword,
      name: 'double sword',
      itemSlot: 'twoHands',
      type: 'melee',
      pDamage: 5,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 5,
      value: 400,
      maxWeaponRange: 25,
      minWeaponRange: 35,
    ),
    Item(
      icon: AppIcons.trident,
      name: 'trident',
      itemSlot: 'twoHands',
      type: 'melee',
      pDamage: 4,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 3,
      value: 400,
      maxWeaponRange: 30,
      minWeaponRange: 40,
    ),
    Item(
      icon: AppIcons.battleAxe,
      name: 'battle axe',
      itemSlot: 'twoHands',
      type: 'melee',
      pDamage: 7,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 8,
      value: 500,
      maxWeaponRange: 20,
      minWeaponRange: 30,
    ),
    Item(
      icon: AppIcons.halberd,
      name: 'halberd',
      itemSlot: 'twoHands',
      type: 'melee',
      pDamage: 6,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 6,
      value: 500,
      maxWeaponRange: 30,
      minWeaponRange: 40,
    ),
    Item(
      icon: AppIcons.warHammer,
      name: 'war hammer',
      itemSlot: 'twoHands',
      type: 'melee',
      pDamage: 8,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 9,
      value: 600,
      maxWeaponRange: 20,
      minWeaponRange: 30,
    ),
    Item(
      icon: AppIcons.greatSword,
      name: 'great sword',
      itemSlot: 'twoHands',
      type: 'melee',
      pDamage: 5,
      pArmor: 2,
      mDamage: 0,
      mArmor: 0,
      weight: 7,
      value: 600,
      maxWeaponRange: 25,
      minWeaponRange: 35,
    ),
  ];

  List<Item> rangedWeapons = [
    Item(
      icon: AppIcons.blowgun,
      name: 'blowgun',
      itemSlot: 'twoHands',
      type: 'ranged',
      pDamage: 1,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      value: 100,
      maxWeaponRange: 60,
      minWeaponRange: 60,
    ),
    Item(
      icon: AppIcons.boomerang,
      name: 'boomerang',
      itemSlot: 'oneHand',
      type: 'ranged',
      pDamage: 1,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      value: 100,
      maxWeaponRange: 40,
      minWeaponRange: 40,
    ),
    Item(
      icon: AppIcons.javelins,
      name: 'javelins',
      itemSlot: 'oneHand',
      type: 'ranged',
      pDamage: 2,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      value: 200,
      maxWeaponRange: 40,
      minWeaponRange: 40,
    ),
    Item(
      icon: AppIcons.grenades,
      name: 'grenades',
      itemSlot: 'oneHand',
      type: 'ranged',
      pDamage: 0,
      pArmor: 0,
      mDamage: 2,
      mArmor: 0,
      weight: 1,
      value: 200,
      maxWeaponRange: 40,
      minWeaponRange: 40,
    ),
    Item(
      icon: AppIcons.shortBow,
      name: 'short bow',
      itemSlot: 'twoHands',
      type: 'ranged',
      pDamage: 3,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 3,
      value: 300,
      maxWeaponRange: 80,
      minWeaponRange: 70,
    ),
    Item(
      icon: AppIcons.kunai,
      name: 'kunai',
      itemSlot: 'oneHand',
      type: 'ranged',
      pDamage: 2,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      value: 300,
      maxWeaponRange: 40,
      minWeaponRange: 40,
    ),
    Item(
      icon: AppIcons.handCrossbow,
      name: 'hand crossbow',
      itemSlot: 'oneHand',
      type: 'ranged',
      pDamage: 2,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 2,
      value: 400,
      maxWeaponRange: 40,
      minWeaponRange: 40,
    ),
    Item(
      icon: AppIcons.longBow,
      name: 'long bow',
      itemSlot: 'twoHands',
      type: 'ranged',
      pDamage: 4,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 4,
      value: 400,
      maxWeaponRange: 120,
      minWeaponRange: 80,
    ),
    Item(
      icon: AppIcons.greatBow,
      name: 'great bow',
      itemSlot: 'twoHands',
      type: 'ranged',
      pDamage: 5,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 5,
      value: 500,
      maxWeaponRange: 160,
      minWeaponRange: 90,
    ),
    Item(
      icon: AppIcons.lightCrossbow,
      name: 'light crossbow',
      itemSlot: 'twoHands',
      type: 'ranged',
      pDamage: 4,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 3,
      value: 500,
      maxWeaponRange: 80,
      minWeaponRange: 70,
    ),
    Item(
      icon: AppIcons.handCannon,
      name: 'hand cannon',
      itemSlot: 'oneHand',
      type: 'ranged',
      pDamage: 3,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      value: 600,
      maxWeaponRange: 40,
      minWeaponRange: 40,
    ),
    Item(
      icon: AppIcons.heavyCrossbow,
      name: 'heavy crossbow',
      itemSlot: 'twoHands',
      type: 'ranged',
      pDamage: 7,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 8,
      value: 600,
      maxWeaponRange: 120,
      minWeaponRange: 80,
    ),
    Item(
      icon: AppIcons.musket,
      name: 'musket',
      itemSlot: 'twoHands',
      type: 'ranged',
      pDamage: 5,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      weight: 3,
      value: 700,
      maxWeaponRange: 60,
      minWeaponRange: 60,
    ),
  ];

  List<Item> magicWeapons = [
    Item(
      icon: AppIcons.magicOrb,
      name: 'magic orb',
      itemSlot: 'oneHand',
      type: 'ranged',
      pDamage: 0,
      pArmor: 0,
      mDamage: 1,
      mArmor: 0,
      weight: 1,
      value: 200,
      maxWeaponRange: 10,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.wand,
      name: 'wand',
      itemSlot: 'oneHand',
      type: 'ranged',
      pDamage: 0,
      pArmor: 0,
      mDamage: 1,
      mArmor: 0,
      weight: 0,
      value: 300,
      maxWeaponRange: 20,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.spellBook,
      name: 'spellBook',
      itemSlot: 'oneHand',
      type: 'ranged',
      pDamage: 0,
      pArmor: 0,
      mDamage: 2,
      mArmor: 0,
      weight: 1,
      value: 500,
      maxWeaponRange: 30,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.magicStaff,
      name: 'magic staff',
      itemSlot: 'twoHands',
      type: 'ranged',
      pDamage: 0,
      pArmor: 0,
      mDamage: 5,
      mArmor: 0,
      weight: 5,
      value: 700,
      maxWeaponRange: 50,
      minWeaponRange: 0,
    ),
  ];

  List<Item> armor = [
    Item(
      icon: AppIcons.boots,
      name: 'boots',
      itemSlot: 'feet',
      type: 'armor',
      pDamage: 0,
      pArmor: 1,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      value: 100,
      maxWeaponRange: 0,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.gloves,
      name: 'gloves',
      itemSlot: 'hands',
      type: 'armor',
      pDamage: 0,
      pArmor: 1,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      value: 100,
      maxWeaponRange: 0,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.buckler,
      name: 'buckler',
      itemSlot: 'oneHand',
      type: 'armor',
      pDamage: 0,
      pArmor: 1,
      mDamage: 0,
      mArmor: 0,
      weight: 0,
      value: 200,
      maxWeaponRange: 0,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.magicSandals,
      name: 'magic sandals',
      itemSlot: 'feet',
      type: 'armor',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 1,
      weight: 1,
      value: 200,
      maxWeaponRange: 0,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.helmet,
      name: 'helmet',
      itemSlot: 'head',
      type: 'armor',
      pDamage: 0,
      pArmor: 2,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      value: 300,
      maxWeaponRange: 0,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.lightShield,
      name: 'light shield',
      itemSlot: 'oneHand',
      type: 'armor',
      pDamage: 0,
      pArmor: 2,
      mDamage: 0,
      mArmor: 0,
      weight: 1,
      value: 300,
      maxWeaponRange: 0,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.lightArmor,
      name: 'light armor',
      itemSlot: 'body',
      type: 'armor',
      pDamage: 0,
      pArmor: 4,
      mDamage: 0,
      mArmor: 0,
      weight: 4,
      value: 400,
      maxWeaponRange: 0,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.magicRobe,
      name: 'magic robe',
      itemSlot: 'body',
      type: 'armor',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 2,
      weight: 2,
      value: 400,
      maxWeaponRange: 0,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.heavyShield,
      name: 'heavy shield',
      itemSlot: 'oneHand',
      type: 'armor',
      pDamage: 0,
      pArmor: 4,
      mDamage: 0,
      mArmor: 0,
      weight: 3,
      value: 500,
      maxWeaponRange: 0,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.fullHelmet,
      name: 'full helmet',
      itemSlot: 'head',
      type: 'armor',
      pDamage: 0,
      pArmor: 4,
      mDamage: 0,
      mArmor: 0,
      weight: 2,
      value: 600,
      maxWeaponRange: 0,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.magicShield,
      name: 'magic shield',
      itemSlot: 'oneHand',
      type: 'armor',
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 3,
      weight: 3,
      value: 600,
      maxWeaponRange: 0,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.heavyArmor,
      name: 'heavy armor',
      itemSlot: 'body',
      type: 'armor',
      pDamage: 0,
      pArmor: 7,
      mDamage: 0,
      mArmor: 0,
      weight: 7,
      value: 700,
      maxWeaponRange: 0,
      minWeaponRange: 0,
    ),
  ];

  List<Item> ancient = [
    Item(
      icon: AppIcons.ancientSword,
      name: 'ancient sword',
      itemSlot: 'oneHand',
      type: 'melee',
      pDamage: 3,
      pArmor: 0,
      mDamage: 2,
      mArmor: 0,
      weight: 2,
      value: 1600,
      maxWeaponRange: 15,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.ancientWarAxe,
      name: 'ancient war axe',
      itemSlot: 'twoHands',
      type: 'melee',
      pDamage: 6,
      pArmor: 0,
      mDamage: 2,
      mArmor: 0,
      weight: 4,
      value: 1700,
      maxWeaponRange: 20,
      minWeaponRange: 25,
    ),
    Item(
      icon: AppIcons.ancientBow,
      name: 'ancient bow',
      itemSlot: 'twoHands',
      type: 'ranged',
      pDamage: 4,
      pArmor: 0,
      mDamage: 2,
      mArmor: 0,
      weight: 1,
      value: 1600,
      maxWeaponRange: 250,
      minWeaponRange: 90,
    ),
    Item(
      icon: AppIcons.ancientSpellBook,
      name: 'ancient spellbook',
      itemSlot: 'oneHand',
      type: 'ranged',
      pDamage: 0,
      pArmor: 0,
      mDamage: 6,
      mArmor: 0,
      weight: 2,
      value: 1900,
      maxWeaponRange: 40,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.ancientGloves,
      name: 'ancient gloves',
      itemSlot: 'hands',
      type: 'armor',
      pDamage: 0,
      pArmor: 1,
      mDamage: 0,
      mArmor: 1,
      weight: 0,
      value: 800,
      maxWeaponRange: 0,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.ancientBoots,
      name: 'ancient boots',
      itemSlot: 'feet',
      type: 'armor',
      pDamage: 0,
      pArmor: 2,
      mDamage: 0,
      mArmor: 1,
      weight: 1,
      value: 900,
      maxWeaponRange: 0,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.ancientHelmet,
      name: 'ancient helmet',
      itemSlot: 'head',
      type: 'armor',
      pDamage: 0,
      pArmor: 4,
      mDamage: 0,
      mArmor: 2,
      weight: 2,
      value: 1200,
      maxWeaponRange: 0,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.ancientShield,
      name: 'ancient shield',
      itemSlot: 'oneHand',
      type: 'armor',
      pDamage: 0,
      pArmor: 3,
      mDamage: 0,
      mArmor: 2,
      weight: 2,
      value: 1600,
      maxWeaponRange: 0,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.ancientArmor,
      name: 'ancient armor',
      itemSlot: 'body',
      type: 'armor',
      pDamage: 0,
      pArmor: 5,
      mDamage: 0,
      mArmor: 2,
      weight: 3,
      value: 1600,
      maxWeaponRange: 0,
      minWeaponRange: 0,
    ),
  ];

  List<Item> consumable = [
    Item(
      icon: AppIcons.ward,
      name: 'ward',
      description: 'Reveals an area around you.',
      itemSlot: 'consumable',
      type: 'consumable',
      weight: 1,
      value: 100,
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      maxWeaponRange: 0,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.food,
      name: 'food',
      description: 'Heals 1-3 HP.',
      itemSlot: 'consumable',
      type: 'consumable',
      weight: 1,
      value: 100,
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      maxWeaponRange: 0,
      minWeaponRange: 0,
    ),
    Item(
      icon: AppIcons.healingPotion,
      name: 'healing potion',
      description: 'Heals 3-6 HP.',
      itemSlot: 'consumable',
      type: 'consumable',
      weight: 1,
      value: 300,
      pDamage: 0,
      pArmor: 0,
      mDamage: 0,
      mArmor: 0,
      maxWeaponRange: 0,
      minWeaponRange: 0,
    ),
  ];
}
